apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backend-config
data:
  BROADCAST_SERVICE_ENABLED: {{ .Values.config.backend.broadcastServiceEnabled | quote }}
  FILE_SERVICE_ENABLED: "false" # @TODO: Enable file-server
  HOSTNAME: {{ .Values.ingress.baseDomain | quote }}
  TLS_ENABLED: {{ .Values.ingress.tlsEnabled | quote }}
  CACHE_SERVICE_RAM: {{ .Values.config.backend.cacheServiceRam | quote }}
  CACHE_SERVICE_INCLUDE_FILES: {{ .Values.config.backend.cacheServiceIncludeFiles | quote }}
  PORT_OF_REVERSE_PROXY: {{ .Values.ingress.httpPort | quote }}
  TLS_PORT_OF_REVERSE_PROXY: {{ .Values.ingress.httpsPort | quote }}
