apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backend-config
data:
  HOSTNAME: {{ .Values.ingress.baseDomain | quote }}
  BROADCASTER_ENABLED: {{ .Values.config.backend.broadcasterEnabled | quote }}
  FILE_SERVER_ENABLED: {{ .Values.config.backend.fileServerEnabled | quote }}
  REDIS_CACHE_FILES: {{ .Values.config.backend.redisCacheFiles | quote }}
