apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
type: Opaque
data:
  REDIS_PASSWORD: {{ .Values.secret.backend.redisPassword | b64enc }}
  MYSQL_USER: {{ .Values.secret.backend.mysqlUser | b64enc }}
  MYSQL_PASSWORD: {{ .Values.secret.backend.mysqlPassword | b64enc }}
  PASSWORD_SALT: {{ .Values.secret.backend.passwordSalt | b64enc }}
