variables:
  DOCKER_TLS_CERTDIR: ''
  DOCKER_DRIVER: overlay2
  GITLAB_REGISTRY_IMAGE_BASE: $CI_REGISTRY_IMAGE
  DEP_PROXY_PREFIX: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}
  BACKEND_IMAGE_NAME: "iqbberlin/testcenter-backend"
  FRONTEND_IMAGE_NAME: "iqbberlin/testcenter-frontend"
  BROADCASTER_IMAGE_NAME: "iqbberlin/testcenter-broadcaster"
  FILE_SERVER_IMAGE_NAME: "iqbberlin/testcenter-file-server"
  E2E_IMAGE_NAME: "testcenter-e2e"

stages:
  - build
  - test
  - test-e2e
  - deploy

workflow:
  rules:
    - if: '$CI_COMMIT_TAG =~ /^((0|([1-9][0-9]*)))\.((0|([1-9][0-9]*)))\.((0|([1-9][0-9]*)))$/'
      variables:
        PIPELINE_TYPE: "release"
    - if: $CI_COMMIT_TAG
      variables:
        PIPELINE_TYPE: "pre-release"
    - if: $CI_PIPELINE_SOURCE == "external_pull_request_event"
      variables:
        PIPELINE_TYPE: "pr"
    - if: $CI_PIPELINE_SOURCE == "web"
      variables:
        PIPELINE_TYPE: "web"
    - if: $CI_COMMIT_BRANCH == "master"
      variables:
        PIPELINE_TYPE: "web"
    - when: always

image: ${DEP_PROXY_PREFIX}/docker:28.2

services:
  - name: ${DEP_PROXY_PREFIX}/docker:28.2-dind
    variables:
      HEALTHCHECK_TCP_PORT: "2375"
    entrypoint: [ "sh", "-c", "dockerd-entrypoint.sh --mtu=1392" ]
    alias: docker


.gitlab_login:
  before_script:
    - echo $CI_DEPENDENCY_PROXY_PASSWORD | docker login -u $CI_DEPENDENCY_PROXY_USER
      --password-stdin $CI_DEPENDENCY_PROXY_SERVER
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER
      --password-stdin $CI_REGISTRY
  after_script:
    - docker logout $CI_DEPENDENCY_PROXY_SERVER
    - docker logout $CI_REGISTRY

.dockerhub_login:
  before_script:
    - echo "$DOCKERHUB_PASSWORD" | docker login -u $DOCKERHUB_USER --password-stdin
  after_script:
    - docker logout

include:
  - local: scripts/ci/backend.yml
  - local: scripts/ci/frontend.yml
  - local: scripts/ci/e2e.yml

build-doc:
  stage: deploy
  rules:
    - if: '$PIPELINE_TYPE == "release"'
      when: on_success
    - when: never
  image: node:22
  script:
    - npm i
    - mkdir tmp
    - npm run frontend:update-compodoc
    - npm run broadcaster:update-compodoc
    - npm run backend:update-specs
    - npm run create-docs
  artifacts:
    paths:
      - docs/index.md
      - docs/pages/booklet-config.md
      - docs/pages/test-mode.md
      - docs/dist/api/index.html
      - docs/dist/api/specs.yml
      - docs/dist/custom-texts.md # TODO falscher Pfad
      - docs/dist/test-session-super-states.html
      - docs/dist/compodoc-frontend/*
      - docs/dist/compodoc-broadcaster/*
    expire_in: 30 minutes

pages:
  stage: deploy
  rules:
   - if: '$PIPELINE_TYPE == "release"'
     when: on_success
   - when: never
  needs:
    - build-doc
  script:
    - echo "$PIPELINE_TYPE"
    - docker build --progress plain --pull --target jekyll
      --file docs/Dockerfile
      --tag ${CI_REGISTRY_IMAGE}/jekyll .
    - mkdir public
    - docker run --volume $(pwd)/public/:/usr/src/testcenter/public/ --volume $(pwd)/docs/:/usr/src/testcenter/docs/ ${CI_REGISTRY_IMAGE}/jekyll;
  artifacts:
    paths:
      - public
  pages:  # specifies that this is a Pages job and publishes the default public directory
    path_prefix: "$CI_COMMIT_BRANCH"

.push-prod-template:
  stage: deploy
  before_script:
    - !reference [ .gitlab_login, before_script ]
    - !reference [ .dockerhub_login, before_script ]
    - docker pull -q ${GITLAB_REGISTRY_IMAGE_BASE}/${BACKEND_IMAGE_NAME}:${CI_COMMIT_SHA}
    - docker pull -q ${GITLAB_REGISTRY_IMAGE_BASE}/${FRONTEND_IMAGE_NAME}:${CI_COMMIT_SHA}
    - docker pull -q ${GITLAB_REGISTRY_IMAGE_BASE}/${BROADCASTER_IMAGE_NAME}:${CI_COMMIT_SHA}
    - docker pull -q ${GITLAB_REGISTRY_IMAGE_BASE}/${FILE_SERVER_IMAGE_NAME}:${CI_COMMIT_SHA}
  after_script:
    - !reference [ .gitlab_login, after_script ]
    - !reference [ .dockerhub_login, after_script ]

push-pre-release:
  extends: .push-prod-template
  rules:
    - if: '$PIPELINE_TYPE == "pre-release"'
      when: on_success
    - when: never
  script:
    - docker tag ${GITLAB_REGISTRY_IMAGE_BASE}/${BACKEND_IMAGE_NAME}:${CI_COMMIT_SHA} ${BACKEND_IMAGE_NAME}:${CI_COMMIT_TAG}
    - docker tag ${GITLAB_REGISTRY_IMAGE_BASE}/${FRONTEND_IMAGE_NAME}:${CI_COMMIT_SHA} ${FRONTEND_IMAGE_NAME}:${CI_COMMIT_TAG}
    - docker tag ${GITLAB_REGISTRY_IMAGE_BASE}/${BROADCASTER_IMAGE_NAME}:${CI_COMMIT_SHA} ${BROADCASTER_IMAGE_NAME}:${CI_COMMIT_TAG}
    - docker tag ${GITLAB_REGISTRY_IMAGE_BASE}/${FILE_SERVER_IMAGE_NAME}:${CI_COMMIT_SHA} ${FILE_SERVER_IMAGE_NAME}:${CI_COMMIT_TAG}
    - docker push -q ${BACKEND_IMAGE_NAME}:${CI_COMMIT_TAG}
    - docker push -q ${FRONTEND_IMAGE_NAME}:${CI_COMMIT_TAG}
    - docker push -q ${BROADCASTER_IMAGE_NAME}:${CI_COMMIT_TAG}
    - docker push -q ${FILE_SERVER_IMAGE_NAME}:${CI_COMMIT_TAG}

push-release:
  extends: .push-prod-template
  needs:
    - pages
  rules:
    - if: '$PIPELINE_TYPE == "release"'
      when: on_success
    - when: never
  script:
    - docker tag ${CI_REGISTRY_IMAGE}/${BACKEND_IMAGE_NAME}:${CI_COMMIT_SHA} ${BACKEND_IMAGE_NAME}:${CI_COMMIT_TAG}
    - docker tag ${CI_REGISTRY_IMAGE}/${BACKEND_IMAGE_NAME}:${CI_COMMIT_SHA} ${BACKEND_IMAGE_NAME}:latest
    - docker tag ${CI_REGISTRY_IMAGE}/${FRONTEND_IMAGE_NAME}:${CI_COMMIT_SHA} ${FRONTEND_IMAGE_NAME}:${CI_COMMIT_TAG}
    - docker tag ${CI_REGISTRY_IMAGE}/${FRONTEND_IMAGE_NAME}:${CI_COMMIT_SHA} ${FRONTEND_IMAGE_NAME}:latest
    - docker tag ${CI_REGISTRY_IMAGE}/${BROADCASTER_IMAGE_NAME}:${CI_COMMIT_SHA} ${BROADCASTER_IMAGE_NAME}:${CI_COMMIT_TAG}
    - docker tag ${CI_REGISTRY_IMAGE}/${BROADCASTER_IMAGE_NAME}:${CI_COMMIT_SHA} ${BROADCASTER_IMAGE_NAME}:latest
    - docker tag ${CI_REGISTRY_IMAGE}/${FILE_SERVER_IMAGE_NAME}:${CI_COMMIT_SHA} ${FILE_SERVER_IMAGE_NAME}:${CI_COMMIT_TAG}
    - docker tag ${CI_REGISTRY_IMAGE}/${FILE_SERVER_IMAGE_NAME}:${CI_COMMIT_SHA} ${FILE_SERVER_IMAGE_NAME}:latest
    - docker push --quiet --all-tags ${BACKEND_IMAGE_NAME}
    - docker push --quiet --all-tags ${FRONTEND_IMAGE_NAME}
    - docker push --quiet --all-tags ${BROADCASTER_IMAGE_NAME}
    - docker push --quiet --all-tags ${FILE_SERVER_IMAGE_NAME}
