stages:
  - test

variables:
  BASE_IMAGE: docker:28.2
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DAEMON_OPTIONS: "--mtu=${DOCKER_SERVICE_MTU}"
  DOCKER_SERVICE_MTU: 1392
  DOCKER_TLS_CERTDIR: ''

image: docker:28.2

services:
  - name: docker:28.2-dind
    variables:
      HEALTHCHECK_TCP_PORT: "2375"
    entrypoint: [ "sh", "-c", "dockerd-entrypoint.sh $DOCKER_DAEMON_OPTIONS" ]
    alias: docker

test-frontend-unit:
  stage: test
  image: node:22-bookworm
  before_script:
    - cd frontend
    - apt-get update && apt-get install -y --no-install-recommends chromium
    - npm ci --no-fund
  script:
    - ng test --watch=false --code-coverage
  artifacts:
    paths:
      - docs/dist/test-coverage-frontend-unit/*
    expire_in: 30 minutes