#TODO schneller pre-release
#TODO brauchen unit tests fuer doku
#TODO Tags auf anderen Branches sollten kein release, schon garkein doklu update triggern
# -> geht nur wenn manual approval for release jobs
#TODO falls doku bauen failt, ist der rest auch wertlos

variables:
  DOCKER_TLS_CERTDIR: ''
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test
  - deploy

workflow:
  rules:
    # Tags → release pipeline
    - if: $CI_COMMIT_TAG
      variables:
        PIPELINE_TYPE: "pre-release"
    - if: '$CI_COMMIT_TAG =~ /^((0|([1-9][0-9]*)))\.((0|([1-9][0-9]*)))\.((0|([1-9][0-9]*)))$/'
      variables:
        PIPELINE_TYPE: "release"
    # Pull requests
    - if: $CI_PIPELINE_SOURCE == "external_pull_request_event"
      variables:
        PIPELINE_TYPE: "pr"
    - if: $CI_PIPELINE_SOURCE == "web"
      variables:
        PIPELINE_TYPE: "web"
    # Otherwise, don't run
    - when: always

image: docker:28.2
services:
  - name: docker:28.2-dind

.docker_login: &docker_login
  - export DOCKERHUB_PROXY=
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
.docker_logout: &docker_logout
  - docker logout "$CI_REGISTRY"

include:
  - local: scripts/ci/backend.yml
  - local: scripts/ci/frontend.yml

build-doc:
  stage: deploy
  rules:
    - if: '$PIPELINE_TYPE == "release"'
      when: on_success
    - when: never
  image: node:22
  script:
    - npm i
    - mkdir tmp
    - npm run frontend:update-compodoc
    - npm run broadcaster:update-compodoc
    - npm run backend:update-specs
    - npm run create-docs
  artifacts:
    paths:
      - docs/index.md
      - docs/pages/booklet-config.md
      - docs/pages/test-mode.md
      - docs/dist/api/index.html
      - docs/dist/api/specs.yml
      - docs/dist/custom-texts.md # TODO falscher Pfad
      - docs/dist/test-session-super-states.html
      - docs/dist/compodoc-frontend/*
      - docs/dist/compodoc-broadcaster/*
    expire_in: 30 minutes

pages-test:
  stage: deploy
  rules:
   - if: '$PIPELINE_TYPE == "release"'
     when: on_success
   - when: never
  needs:
    - build-doc
  script:
    - echo "$PIPELINE_TYPE"
    - docker build --progress plain --pull --target jekyll
      --file docs/Dockerfile
      --tag ${CI_REGISTRY_IMAGE}/jekyll .
    - mkdir public
    - docker run --volume $(pwd)/public/:/usr/src/testcenter/public/ --volume $(pwd)/docs/:/usr/src/testcenter/docs/ ${CI_REGISTRY_IMAGE}/jekyll;
  artifacts:
    paths:
      - public
#  pages:  # specifies that this is a Pages job and publishes the default public directory
#    path_prefix: "$CI_COMMIT_BRANCH"
