---
apiVersion: v1
kind: Namespace
metadata:
  name: tc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: testcenter-config
  namespace: tc
data:
  HOSTNAME: "minikube-ip-defined-in-hosts.example"
  TLS_PORT: "443"
  TLS_ENABLED: "on"
  MYSQL_DATABASE: "iqb_tba_testcenter"
  MYSQL_USER: "iqb_tba_db_user"
  BROADCAST_SERVICE_ENABLED: "true"
  FILE_SERVICE_ENABLED: "true"
  CACHE_SERVICE_RAM: "1073741824"
  CACHE_SERVICE_INCLUDE_FILES: "false"
  DOCKER_DAEMON_MTU: "1442"
  DOCKERHUB_PROXY: ''
  RESTART_POLICY: "no"
  CACHE_SERVICE_ADDRESS_FOR_LUA: "testcenter-cache-service.tc.svc.cluster.local"
---
apiVersion: v1
kind: Secret
metadata:
  name: testcenter-secrets
  namespace: tc
stringData:
  PASSWORD_SALT: "t"
  MYSQL_ROOT_PASSWORD: "o8en6jSGLyVKNZUN"
  MYSQL_PASSWORD: "fEaU5COJYXv2atau"

---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: tc
type: kubernetes.io/tls
data:
  tls.crt: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURjakNDQWxxZ0F3SUJBZ0lVUmljZklzVXJMVWJmSUR5OUd3Y2hiR3lSTGtvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0x6RXRNQ3NHQTFVRUF3d2tiV2x1YVd0MVltVXRhWEF0WkdWbWFXNWxaQzFwYmkxb2IzTjBjeTVsZUdGdApjR3hsTUI0WERUSTBNVEF6TVRFME1qYzFORm9YRFRJMU1UQXpNVEUwTWpjMU5Gb3dMekV0TUNzR0ExVUVBd3drCmJXbHVhV3QxWW1VdGFYQXRaR1ZtYVc1bFpDMXBiaTFvYjNOMGN5NWxlR0Z0Y0d4bE1JSUJJakFOQmdrcWhraUcKOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQW9DVCtEUUFkTGRubi91dzlkTEN3N3RRYnFhWDE2WE4wQk5hTwpIVk5vV2V0dGtBanJSYzJUVUdKL0lMeFk4WnN6alRXUEtza2JOdzkzSVdBZW45UHFOdHl4T1BWdDlkMm1XZlFnClQyQS91dU94NnlFMFJ3Y0ZDRE9TNVpFUHBWcldEcmlBL29IWWlrZWoySEUrN2tNdGVLNDhUUHJ4WmY0OTFSQisKWEJMOVJQOFFZYWlwY21sT1dFSEgzS2c3UVFSdENzZXRrUUNxbThQdmdZWGdmUTlHZTgzcDgzOG1BcEJoWi84TwovT3VxNlBrYng3Ni9NOTdvWWlRWlcwR3hZendEcFVWQlpSOXRwcmF1RExPeFZRMFlid2VxWno4N0VCaktyOHR4Ckt6UTBnTU5waEFqWXptbzJNZzRpc250d3hnL0Q2Q1Q5K2VhcHVRUmtEblVOcUVMSit3SURBUUFCbzRHRk1JR0MKTUIwR0ExVWREZ1FXQkJSS3AralZBWXNzUzJoR3dRYnJnUmkzK2JaSktqQWZCZ05WSFNNRUdEQVdnQlJLcCtqVgpBWXNzUzJoR3dRYnJnUmkzK2JaSktqQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01DOEdBMVVkRVFRb01DYUNKRzFwCmJtbHJkV0psTFdsd0xXUmxabWx1WldRdGFXNHRhRzl6ZEhNdVpYaGhiWEJzWlRBTkJna3Foa2lHOXcwQkFRc0YKQUFPQ0FRRUFWRXozZnZQMFZ2WGpRK3ZlNXFjSjMveXV6WTl6WnczNzJTb0tvMVU3NlJuRFpFdlI4QTlRb254UAplbTkyaGc2ajBOaFVaNkdvRWZHaDdRbDdPMytlNkpxS1J6M3dYQmNyS3ZFWFZ3d3JmbUN4bi9SY2RISlpzYVlWCk5pS0lwQ0FWNVhiaW1ZRnpCbUhJK28xeWk1UEM1d3J6WWpwaWpkNzU4enJ5MUtDZkpsWkt4c1ZIR1lwTTZLbHoKY1AxaFkycklxR1lwVS95TVVielJHYkhUWWlxYm91S1ZrVGJkd3NaNFhSUXZTUS96NnovK1dEd2VpM1YwN0dpTQp4SXJsNFFOTldDUTNUMElRM09Qd0xxOThDZ2xZb1VYaGlabHRzU0VobENKR2JtQlZCVmhieEpjWTFBaTRpeU9XCnNXWGExaXdDMnJtbFlmYjhDazBoWW9FRjdBYXNEQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
  tls.key: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRQ2dKUDROQUIwdDJlZisKN0QxMHNMRHUxQnVwcGZYcGMzUUUxbzRkVTJoWjYyMlFDT3RGelpOUVluOGd2Rmp4bXpPTk5ZOHF5UnMzRDNjaApZQjZmMCtvMjNMRTQ5VzMxM2FaWjlDQlBZRCs2NDdIcklUUkhCd1VJTTVMbGtRK2xXdFlPdUlEK2dkaUtSNlBZCmNUN3VReTE0cmp4TSt2RmwvajNWRUg1Y0V2MUUveEJocUtseWFVNVlRY2ZjcUR0QkJHMEt4NjJSQUtxYncrK0IKaGVCOUQwWjd6ZW56ZnlZQ2tHRm4vdzc4NjZybytSdkh2cjh6M3VoaUpCbGJRYkZqUEFPbFJVRmxIMjJtdHE0TQpzN0ZWRFJodkI2cG5QenNRR01xdnkzRXJORFNBdzJtRUNOak9hall5RGlLeWUzREdEOFBvSlAzNTVxbTVCR1FPCmRRMm9Rc243QWdNQkFBRUNnZ0VBTnhwRGFBbkFBSVRYOUxrb3REd1B4VDJxZndjaHhELzdqYWFkbzYyTlhGTkwKa2FIZ0FsYW45NkxNaDJFSFlhcTdaRDBuazlzNnlBbEVQbkdxVitnODBML0RJd3dmMTlkNlk3MUNXTTJQWUNqMAprU2tOcWRyYWVtWDBoNVVRUXg4c1JFaHI2aWFYY1kwUTdXcVo4cldlc2NXUjdoTHllTnV3UHQyNy9NWno2d2NsCkxpNkpoQTkxZkN0MTNSSHBFZnFQUmZYYUtFMUdsTlhPSHB5Sjloa3FkUmRPVmpGdFR1azhEMi85WWNIUnErRGIKYVkwdUdGdzk0SUJmWW00Mlkyc0tlbWlzcExVclVCQlpibjhEUms4MnZIenk4RndTdUY4V3hoTzFHLzl2MnhsKwpzTWt5djcvQTBPdGhrQTR5ZmtJVVVON09Raiszdll0Y3VyTWVnSzk5TVFLQmdRREw1aXdEYlo4c1R0SHAzUkh1CldUOWJjeDF1aHdpaTdyMUlxT3RXVEFSWkpHdVhoMGNZUHB5ZGJFNU05S1o4amFZSUNKZDM0QmFranJOeFlraDQKZ0VsK3A2MUNwcktic3owZGhYdUlYeDlZb1hpYkVQS0p4Ym1wLzdwTUsyYzdPK0p1Q3NvTFUvbUVkS1l3OWlIRgp6NTZTbXVwRjNQWG1xZjhGOXRjcXFMUjJwd0tCZ1FESkVLbWhlSTFFQjlZK2ZURzg2UzZGQ3I2UTQ1cUxCZ3hjCjBwL3Y1emN5SExkK3kwK0RpRytjWUxwREYwbVIxTXB5SmwwMURnMFUxelRPaWhZZDA0T3NvOVBQbzBXYnNkREgKMUFhVEhWeW0ybnRLVDJLLzZGVklpM0Fzc3hpK0JuNGFueS9TazRBOXFldzl6ZUdlcHIyaVZ1ODJRQ2dHdW02VQpjcE01Y0ZVUWpRS0JnSHpKa0pSRWljOEhLaWN6bWg3Q1ZpazB5WVYwZFErcWh3T3FCZVdadm11RUE2a0lMTFdrCjFCcndSdmVJSDBCSlBKemNEVDliVU9CRFNZVVIvb0pwR1JHL3N5VUFlbjBaOUVSV0JpV08rZE0zZDJXSHVMZ2kKMzU4d0dDYzN4UVVXZ0Z5U2s5YmMvTzlZcU1GOFVXMEx4T082bGJoT0k5eVltN0Jkd28ra0VsWXZBb0dCQUtsawpOVlVKQ0JLUmU2akh0cGlONXhoRTFnbWhCdmtyRGsxQlVXYys1MXg3bndmZVowM01LeU9XeGpWeHNCU0JMbEYvCkNyV0E4ZnBsMkdKTktaYlZOTERFa05UMG05Y3d0bEV6eXBvMGVYTkV5K3Z0OTZid0tMRm1jQW5vbE9hNjk1Q2MKSGlFTkRWUm1ETmFBMWh6Z0l4RmFwa3VSUDJkenQyZXZJMk9YeE1LZEFvR0FGUERRVDJCRWhBTGZHSGVBeHJQTQpLcStkTGhmNnBCUkhMaVY0VHlhNnBEelQ1QURWbXhvZVFscjhJT3ppWjlybUp1V0JzQzhKM3NpTURXbXBvMmc1CmQ5T1RRMVd5VHlDR2tjcElmbVpyTDNsQlZzWjRNOXliVDdQYXFmQ2U0MUptZ0pZMUg2akt4QzY5d3FzYU8xclcKZmxicFJ3UjBtZ1FEN1hjRmZsanpwL1E9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K"