// this file is automatically generated. do not change anything here directly!
export class BookletConfigData {
  loading_mode: 'LAZY' | 'EAGER' = 'LAZY';
  logPolicy: 'disabled' | 'lean' | 'rich' | 'debug' = 'rich';
  browserBehaviour: 'standard' | 'preventNav' = 'standard';
  pagingMode: 'separate' | 'concat-scroll' | 'concat-scroll-snap' = 'separate';
  force_presentation_complete: 'OFF' | 'ALWAYS' | 'ON' = 'OFF';
  force_response_complete: 'OFF' | 'ALWAYS' | 'ON' = 'OFF';
  unit_time_left_warnings: string = '5,1';
  show_end_button_in_player: 'OFF' | 'ALWAYS' | 'ONLY_LAST_UNIT' = 'OFF';
  restore_current_page_on_return: 'OFF' | 'ON' = 'OFF';
  allow_player_to_terminate_test: 'OFF' | 'LAST_UNIT' | 'ON' = 'ON';
  lock_test_on_termination: 'ON' | 'OFF' = 'OFF';
  ask_for_fullscreen: 'ON' | 'OFF' = 'OFF';
  unit_responses_buffer_time: string = '5000';
  unit_state_buffer_time: string = '6000';
  test_state_buffer_time: string = '1000';
  header_content: 'NONE' | 'BOOKLET_LABEL' | 'BLOCK_LABEL' | 'UNIT_LABEL' = 'NONE';
  navbar_unit_label: 'HIDDEN' | 'INDEX' | 'LABEL' = 'INDEX';
  navbar_unit_controls_hidden: 'TRUE' | 'FALSE' = 'FALSE';
  navbar_page_label: 'HIDDEN' | 'INDEX' | 'LABEL' | 'LIST' = 'INDEX';
  navbar_page_controls_hidden: 'TRUE' | 'FALSE' = 'FALSE';
  toolbar_show_unit_title: 'TRUE' | 'FALSE' = 'TRUE';
  toolbar_show_unit_list: 'TRUE' | 'FALSE' = 'FALSE';
  toolbar_show_fullscreen_button: 'TRUE' | 'FALSE' = 'FALSE';
  toolbar_show_reload_button: 'TRUE' | 'FALSE' = 'FALSE';
  toolbar_show_time_left: 'TRUE' | 'FALSE' = 'FALSE';
  silent_mode: 'TRUE' | 'FALSE' = 'FALSE';
}
