// this file is automatically generated. do not change anything here directly!
export class BookletConfigData {
  loading_mode: 'LAZY' | 'EAGER' = 'LAZY';
  logPolicy: 'disabled' | 'lean' | 'rich' | 'debug' = 'rich';
  pagingMode: 'separate' | 'concat-scroll' | 'concat-scroll-snap' = 'separate';
  page_navibuttons: 'OFF' | 'SEPARATE_BOTTOM' = 'SEPARATE_BOTTOM';
  unit_navibuttons: 'OFF' | 'ARROWS_ONLY' | 'FORWARD_ONLY' | 'FULL' = 'FULL';
  unit_menu: 'OFF' | 'FULL' = 'OFF';
  force_presentation_complete: 'OFF' | 'ALWAYS' | 'ON' = 'OFF';
  force_response_complete: 'OFF' | 'ALWAYS' | 'ON' = 'OFF';
  controller_design: '2018' | '2022' = '2022';
  unit_screenheader: 'OFF' | 'WITH_UNIT_TITLE' | 'WITH_BOOKLET_TITLE' | 'WITH_BLOCK_TITLE' | 'EMPTY' = 'EMPTY';
  unit_title: 'OFF' | 'ON' = 'ON';
  unit_show_time_left: 'OFF' | 'ON' = 'OFF';
  unit_time_left_warnings: string = '5,1';
  show_end_button_in_player: 'OFF' | 'ALWAYS' | 'ONLY_LAST_UNIT' = 'OFF';
  restore_current_page_on_return: 'OFF' | 'ON' = 'OFF';
  allow_player_to_terminate_test: 'OFF' | 'LAST_UNIT' | 'ON' = 'ON';
  lock_test_on_termination: 'ON' | 'OFF' = 'OFF';
  ask_for_fullscreen: 'ON' | 'OFF' = 'OFF';
  show_fullscreen_button: 'ON' | 'OFF' = 'OFF';
  show_reload_button: 'ON' | 'OFF' = 'OFF';
  unit_responses_buffer_time: string = '5000';
  unit_state_buffer_time: string = '6000';
  test_state_buffer_time: string = '1000';
}
