// this file is automatically generated. do not change anything here directly!
export class TestModeData {
  alwaysNewSession: boolean = true;
  canReview: boolean = false;
  saveResponses: boolean = false;
  forceTimeRestrictions: boolean = false;
  forceNaviRestrictions: boolean = false;
  monitorable: boolean = false;
  showCode: boolean = true;
  showTimeLeft: boolean = false;
  showUnitMenu: boolean = false;
  receiveRemoteCommands: boolean = false;
  canChangeStateOptions: boolean = true;
  lockAfterFailedLogins: boolean = false;

  static modes = {
    'RUN-DEMO': {
      alwaysNewSession: true,
      monitorable: false,
      canReview: false,
      saveResponses: false,
      forceTimeRestrictions: false,
      forceNaviRestrictions: false,
      showCode: true,
      showTimeLeft: false,
      showUnitMenu: false,
      receiveRemoteCommands: false,
      canChangeStateOptions: true,
      lockAfterFailedLogins: false
    },
    'MONITOR-GROUP': {
      alwaysNewSession: false,
      monitorable: false,
      canReview: false,
      saveResponses: false,
      forceTimeRestrictions: false,
      forceNaviRestrictions: false,
      showCode: true,
      showTimeLeft: false,
      showUnitMenu: false,
      receiveRemoteCommands: false,
      canChangeStateOptions: true,
      lockAfterFailedLogins: true
    },
    'MONITOR-STUDY': {
      alwaysNewSession: false,
      monitorable: false,
      canReview: false,
      saveResponses: false,
      forceTimeRestrictions: false,
      forceNaviRestrictions: false,
      showCode: true,
      showTimeLeft: false,
      showUnitMenu: false,
      receiveRemoteCommands: false,
      canChangeStateOptions: true,
      lockAfterFailedLogins: true
    },
    'RUN-HOT-RETURN': {
      alwaysNewSession: false,
      monitorable: true,
      canReview: false,
      saveResponses: true,
      forceTimeRestrictions: true,
      forceNaviRestrictions: true,
      showCode: false,
      showTimeLeft: false,
      showUnitMenu: false,
      receiveRemoteCommands: true,
      canChangeStateOptions: false,
      lockAfterFailedLogins: false
    },
    'RUN-HOT-RESTART': {
      alwaysNewSession: true,
      monitorable: true,
      canReview: false,
      saveResponses: true,
      forceTimeRestrictions: true,
      forceNaviRestrictions: true,
      showCode: false,
      showTimeLeft: false,
      showUnitMenu: false,
      receiveRemoteCommands: true,
      canChangeStateOptions: false,
      lockAfterFailedLogins: false
    },
    'RUN-REVIEW': {
      alwaysNewSession: false,
      monitorable: false,
      canReview: true,
      saveResponses: false,
      forceTimeRestrictions: false,
      forceNaviRestrictions: false,
      showCode: true,
      showTimeLeft: true,
      showUnitMenu: true,
      receiveRemoteCommands: false,
      canChangeStateOptions: true,
      lockAfterFailedLogins: false
    },
    'RUN-TRIAL': {
      alwaysNewSession: false,
      monitorable: true,
      canReview: true,
      saveResponses: true,
      forceTimeRestrictions: false,
      forceNaviRestrictions: false,
      showCode: true,
      showTimeLeft: true,
      showUnitMenu: true,
      receiveRemoteCommands: false,
      canChangeStateOptions: true,
      lockAfterFailedLogins: false
    },
    'RUN-SIMULATION': {
      alwaysNewSession: false,
      monitorable: false,
      canReview: false,
      saveResponses: false,
      forceTimeRestrictions: true,
      forceNaviRestrictions: true,
      showCode: false,
      showTimeLeft: false,
      showUnitMenu: false,
      receiveRemoteCommands: false,
      canChangeStateOptions: false,
      lockAfterFailedLogins: false
    },
    'SYS-CHECK-LOGIN': {
      alwaysNewSession: true,
      monitorable: false,
      canReview: false,
      saveResponses: false,
      forceTimeRestrictions: false,
      forceNaviRestrictions: false,
      showCode: false,
      showTimeLeft: false,
      showUnitMenu: false,
      receiveRemoteCommands: false,
      lockAfterFailedLogins: false
    }
  };

  static labels = {
    'RUN-DEMO': 'Nur Ansicht (Demo)',
    'MONITOR-GROUP': 'Testgruppen-Monitor (Demo)',
    'MONITOR-STUDY': 'Studien-Monitor (Demo)',
    'RUN-HOT-RETURN': 'Durchführung Test/Befragung',
    'RUN-HOT-RESTART': 'Durchführung Test/Befragung',
    'RUN-REVIEW': 'Prüfdurchgang ohne Speichern',
    'RUN-TRIAL': 'Prüfdurchgang mit Speichern und Reviewfunktionalität',
    'RUN-SIMULATION': 'Prüfdurchgang ohne Speichern, ohne Reviewfunktionalität aber mit Beschränkungen',
    'SYS-CHECK-LOGIN': 'Dieser Modus versteckt für alle anderen Logins den System Check. Der Check kann dann nur noch von Logins durchgeführt werden mit diesem Mode'
  };
}
