// this file is automatically generated. do not change anything here directly!
export class TestModeData {
  alwaysNewSession: boolean = false;
  canReview: boolean = false;
  saveResponses: boolean = false;
  forceTimeRestrictions: boolean = false;
  forceNaviRestrictions: boolean = false;
  monitorable: boolean = undefined;
  presetCode: boolean = true;
  showTimeLeft: boolean = false;
  showUnitMenu: boolean = false;
  receiveRemoteCommands: boolean = false;

  static modes = {
    'RUN-DEMO': {
      alwaysNewSession: false,
      canReview: false,
      saveResponses: false,
      forceTimeRestrictions: false,
      forceNaviRestrictions: false,
      presetCode: true,
      showTimeLeft: false,
      showUnitMenu: false,
      receiveRemoteCommands: false
    },
    'MONITOR-GROUP': {
      alwaysNewSession: false,
      canReview: false,
      saveResponses: false,
      forceTimeRestrictions: false,
      forceNaviRestrictions: false,
      presetCode: true,
      showTimeLeft: false,
      showUnitMenu: false,
      receiveRemoteCommands: false
    },
    'MONITOR-STUDY': {
      alwaysNewSession: false,
      canReview: false,
      saveResponses: false,
      forceTimeRestrictions: false,
      forceNaviRestrictions: false,
      presetCode: true,
      showTimeLeft: false,
      showUnitMenu: false,
      receiveRemoteCommands: false
    },
    'RUN-HOT-RETURN': {
      alwaysNewSession: false,
      canReview: false,
      saveResponses: true,
      forceTimeRestrictions: true,
      forceNaviRestrictions: true,
      presetCode: false,
      showTimeLeft: false,
      showUnitMenu: false,
      receiveRemoteCommands: true
    },
    'RUN-HOT-RESTART': {
      alwaysNewSession: true,
      canReview: false,
      saveResponses: true,
      forceTimeRestrictions: true,
      forceNaviRestrictions: true,
      presetCode: false,
      showTimeLeft: false,
      showUnitMenu: false,
      receiveRemoteCommands: true
    },
    'RUN-REVIEW': {
      alwaysNewSession: false,
      canReview: true,
      saveResponses: false,
      forceTimeRestrictions: false,
      forceNaviRestrictions: false,
      presetCode: true,
      showTimeLeft: true,
      showUnitMenu: true,
      receiveRemoteCommands: false
    },
    'RUN-TRIAL': {
      alwaysNewSession: false,
      canReview: false,
      saveResponses: true,
      forceTimeRestrictions: true,
      forceNaviRestrictions: true,
      presetCode: true,
      showTimeLeft: false,
      showUnitMenu: false,
      receiveRemoteCommands: false
    }
  };

  static labels = {
    'RUN-DEMO': 'Nur Ansicht (Demo)',
    'MONITOR-GROUP': 'Testgruppen-Monitor (Demo)',
    'MONITOR-STUDY': 'Studien-Monitor (Demo)',
    'RUN-HOT-RETURN': 'Durchführung Test/Befragung',
    'RUN-HOT-RESTART': 'Durchführung Test/Befragung',
    'RUN-REVIEW': 'Prüfdurchgang ohne Speichern',
    'RUN-TRIAL': 'Prüfdurchgang mit Speichern'
  };
}
