apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.secret.db.mysqlRootPassword | b64enc }}
  MYSQL_USER: {{ .Values.secret.db.mysqlUser | b64enc }}
  MYSQL_PASSWORD: {{ .Values.secret.db.mysqlPassword | b64enc }}
