apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
type: Opaque
data:
  DB_USER: {{ .Values.secret.db.user | b64enc }}
  DB_PASSWORD: {{ .Values.secret.db.password | b64enc }}
