apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db
spec:
  selector:
    app: {{ .Release.Name }}-db-pod
  ports:
    - protocol: TCP
      port: 3306
      targetPort: mysql-container
