apiVersion: v1
kind: Service
metadata:
  name: testcenter-db # !!! Hard coded in application as internal address !!! @TODO: Should be '{{ .Release.Name }}-db'
spec:
  selector:
    app: {{ .Release.Name }}-db-pod
  ports:
    - protocol: TCP
      port: 3306
      targetPort: mysql-container
