namespace: tc
environment: dev

traefik:
  name: traefik
  namespace: default
  image:
    tag: v2.11
  port:
    http: 80
    https: 443
    dashboard: 8080
  serviceKind: LoadBalancer
  tlsOption:
    name: default
    minVersion: VersionTLS12
    cipherSuites:
      - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
      - TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
      - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
      - TLS_ECDHE_ECDSA_WITH_RC4_128_SHA
      - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
      - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
    sniStrict: true

config:
  hostname: minikube-ip-defined-in-hosts.example
  port: 30632
  tlsPort: 32532
  tlsEnabled: off
  mysqlDatabase: iqb_tba_testcenter
  mysqlUser: iqb_tba_db_user
  broadcastServiceEnabled: true
  fileServiceEnabled: true
  cacheServiceRam: 1073741824
  cacheServiceIncludeFiles: false
  dockerDaemonMtu: 1500
  dockerhubProxy: ''
  restartPolicy: always
  overwriteInstallation: no
  skipReadFiles: no
  skipDbIntegrity: no
  noSampleData: no
  cacheServiceAddressForLua: testcenter-cache-service.tc.svc.cluster.local

secret:
  passwordSalt: t
  mysqlRootPassword: o8en6jSGLyVKNZUN
  mysqlPassword: fEaU5COJYXv2atau

backend:
  name: backend
  replicas: 1
  port: 80

broadcastingService:
  name: bs
  replicas: 1
  port: 3000
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

cacheService:
  name: cs
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  port: 6379

database:
  name: db
  replicas: 1
  port: 3306

frontend:
  name: fe
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  port: 80

fileService:
  name: fs
  replicas: 1
  port: 80
  configmap:
    name: nginx-fs-config-configmap

volume:
  vodata:
    name: testcenter-backend-vo-data
    storageClassName: standard
    accessMode: ReadWriteOnce
    size: 2Gi
  dbdata:
    name: dbdata
    storageClassName: standard
    accessMode: ReadWriteOnce
    size: 2Gi
  cache:
    name: redis-pvc
    storageClassName: standard
    accessMode: ReadWriteOnce
    size: 5Gi

ingress:
  middleware:
    stripregex:
      fe: stripregexfe
      be: stripregexbe
      fs: stripregexfs
      bs: stripregexbs
    security:
      name: securityheaders