#!/usr/bin/env bash
set -e

mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" <<EOF
CREATE DATABASE IF NOT EXISTS TEST_${MYSQL_DATABASE};
GRANT ALL PRIVILEGES ON TEST_${MYSQL_DATABASE}.* TO '${MYSQL_USER}'@'%';
EOF

echo "Test DB created."
