-- IQB Testcenter — complete PostgreSQL schema.
--
-- This file is hand-maintained, not dumped from a running database.
-- `backend/initialize.php` runs it once against an empty database and then applies every patch in
-- `scripts/database/patches.d` that the version stamped at the end of this file does not already
-- cover. `TestEnvironment::createTestDatabase()` runs it alone to build the test database.
-- Adding a patch therefore means applying the same change here — see docs/agent/database.md.
--
-- Statement order is foreign-key dependency order.

BEGIN;

-- Case-insensitive equality for human-readable text, as the MySQL releases had on most columns.
-- Being non-deterministic, this collation makes PostgreSQL reject LIKE, ILIKE and regular
-- expressions on any column using it ("nondeterministic collations are not supported for LIKE").
-- No query needs that today; where one does, compare with COLLATE "C" in the query itself or make
-- that column deterministic and index lower(...).
CREATE COLLATION IF NOT EXISTS german2_ci (
  provider      = icu,
  locale        = 'de-DE-u-ks-level2',  -- level2: case-insensitive, accent-sensitive
  deterministic = false
);

-- Columns deliberately declared WITHOUT german2_ci fall into two groups:
--
--   1. Identifiers that must match exactly: login_sessions.name, logins.name, logins.source,
--      files.name, file_relations.subject_name and object_name. These were utf8mb3_bin or
--      varbinary in MySQL for that reason. varbinary never carried binary data — it was only a way
--      to force a case-sensitive comparison — so varchar is the faithful translation, not bytea.
--
--   2. Machine-generated or machine-matched values: meta.metaKey and category, test_commands
--      keyword and parameter, everything in unit_data, and the assets and asset_assignment text
--      columns. These compared case-insensitively under MySQL, but only by accident: the patches
--      creating them omitted COLLATE and inherited the mysql:8.4 server default
--      utf8mb4_0900_ai_ci, while every patch that stated a collation chose german2_ci. Their values
--      are generated ids, client-supplied part ids, XML slot names and code literals, and PHP
--      already compares them case-sensitively (see WorkspaceCache::hasAsset()). Case-sensitive is
--      the intended state here; do not "restore" the inherited collation.

CREATE TYPE file_type AS ENUM (
  'Testtakers', 'SysCheck', 'Booklet', 'Unit', 'Resource'
);

CREATE TYPE verona_module_type AS ENUM (
  'player', 'schemer', 'editor', ''
);

CREATE TYPE file_relationship_type AS ENUM (
  'hasBooklet', 'containsUnit', 'usesPlayer', 'usesPlayerResource',
  'isDefinedBy', 'usesScheme', 'unknown'
);

CREATE TYPE attachment_type AS ENUM ('capture-image');

CREATE TYPE assignment_scope AS ENUM ('global', 'group', 'user');

-- InitDAO::clearDB() drops these types by name after dropping the tables, because PostgreSQL keeps
-- them once their consuming tables are gone. Adding a type here means adding it to
-- InitDAO::schemaTypes as well, or --overwrite_existing_installation breaks on the next run.


-- Identity columns are GENERATED BY DEFAULT, not ALWAYS, so that tests, fixtures and restores can
-- insert explicit ids. Doing so does not advance the sequence — backend/test/unit/testdata.sql and
-- InitDAO::createWorkspaceIfMissing() resynchronize it with setval() afterwards.


-- =====================================================================
-- users
-- =====================================================================
CREATE TABLE users (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            varchar(50) COLLATE german2_ci NOT NULL,
  password        varchar(100) COLLATE german2_ci NOT NULL,
  email           varchar(100) COLLATE german2_ci DEFAULT NULL,
  is_superadmin   boolean NOT NULL DEFAULT false,
  pw_set_by_admin boolean NOT NULL DEFAULT false
);


-- =====================================================================
-- workspaces
-- =====================================================================
CREATE TABLE workspaces (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           varchar(50) COLLATE german2_ci NOT NULL,
  workspace_hash varchar(255) COLLATE german2_ci NOT NULL DEFAULT '',
  content_type   varchar(255) COLLATE german2_ci NOT NULL DEFAULT 'mixed'
);


-- =====================================================================
-- login_session_groups
-- =====================================================================
-- Every timestamp column in this schema is timestamptz: MySQL TIMESTAMP stored UTC and converted
-- to the session timezone, and only timestamptz does the same. Run the server in UTC.
CREATE TABLE login_session_groups (
  workspace_id  bigint NOT NULL,
  group_label   text COLLATE german2_ci NOT NULL,
  group_name    varchar(100) COLLATE german2_ci NOT NULL,
  token         varchar(50) COLLATE german2_ci NOT NULL,
  last_modified timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (workspace_id, group_name),
  CONSTRAINT login_session_groups_unique_token UNIQUE (token)
);


-- =====================================================================
-- login_sessions
-- =====================================================================
CREATE TABLE login_sessions (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         varchar(50) NOT NULL,   -- no german2_ci: login names must match exactly
  workspace_id bigint NOT NULL,
  token        varchar(50) COLLATE german2_ci NOT NULL,
  group_name   varchar(100) COLLATE german2_ci NOT NULL,
  CONSTRAINT unique_login_session UNIQUE (name, workspace_id),
  CONSTRAINT fk_login_workspace
    FOREIGN KEY (workspace_id) REFERENCES workspaces (id) ON DELETE CASCADE,
  CONSTRAINT login_session_groups_fk
    FOREIGN KEY (workspace_id, group_name)
    REFERENCES login_session_groups (workspace_id, group_name)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX index_fk_login_workspace   ON login_sessions (workspace_id);
CREATE INDEX index_fk_logins            ON login_sessions (name);
CREATE INDEX login_sessions_token_index ON login_sessions (token);
CREATE INDEX login_sessions_groups_fk   ON login_sessions (workspace_id, group_name);


-- =====================================================================
-- person_sessions
-- =====================================================================
CREATE TABLE person_sessions (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code              varchar(50) COLLATE german2_ci NOT NULL,
  login_sessions_id bigint NOT NULL,
  valid_until       timestamptz DEFAULT NULL,
  token             varchar(50) COLLATE german2_ci DEFAULT NULL,
  name_suffix       varchar(100) COLLATE german2_ci DEFAULT NULL,
  -- name_suffix is nullable, so this constraint permits any number of rows that leave it NULL.
  -- SessionDAO relies on that and resolves suffix collisions by retrying on a unique violation.
  CONSTRAINT unique_person_session UNIQUE (login_sessions_id, name_suffix),
  CONSTRAINT fk_person_login
    FOREIGN KEY (login_sessions_id) REFERENCES login_sessions (id) ON DELETE CASCADE
);

CREATE INDEX index_fk_person_login       ON person_sessions (login_sessions_id);
CREATE INDEX person_sessions_token_index ON person_sessions (token);


-- =====================================================================
-- tests
-- =====================================================================
CREATE TABLE tests (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name             varchar(250) COLLATE german2_ci NOT NULL,
  person_id        bigint NOT NULL,
  laststate        text COLLATE german2_ci,
  locked           boolean NOT NULL DEFAULT false,
  label            varchar(100) COLLATE german2_ci DEFAULT NULL,
  running          boolean NOT NULL DEFAULT false,
  timestamp_server timestamptz DEFAULT CURRENT_TIMESTAMP,
  file_id          varchar(120) COLLATE german2_ci NOT NULL,
  CONSTRAINT tests_person_id_name_key UNIQUE (person_id, name),
  CONSTRAINT fk_booklet_person
    FOREIGN KEY (person_id) REFERENCES person_sessions (id) ON DELETE CASCADE
);

CREATE INDEX index_fk_booklet_person ON tests (person_id);


-- =====================================================================
-- units
-- =====================================================================
CREATE TABLE units (
  name                varchar(50) COLLATE german2_ci NOT NULL,
  test_id             bigint NOT NULL,
  laststate           text COLLATE german2_ci,
  laststate_update_ts text COLLATE german2_ci,   -- text, not a timestamp: a JSON map of state key -> ms
  original_unit_id    varchar(255) COLLATE german2_ci NOT NULL DEFAULT '',
  PRIMARY KEY (test_id, name),
  CONSTRAINT fk_unit_booklet
    FOREIGN KEY (test_id) REFERENCES tests (id) ON DELETE CASCADE
);

CREATE INDEX index_fk_unit_booklet ON units (test_id);


-- =====================================================================
-- admin_sessions
-- =====================================================================
-- MySQL raised valid_until on every UPDATE (ON UPDATE CURRENT_TIMESTAMP). That is not reproduced:
-- it moved the expiry of a session on any unrelated write, and AdminDAO sets valid_until itself
-- whenever a session is created or renewed.
CREATE TABLE admin_sessions (
  token       varchar(50) COLLATE german2_ci PRIMARY KEY,
  user_id     bigint NOT NULL,
  valid_until timestamptz NOT NULL,
  CONSTRAINT fk_users_admintokens
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX index_fk_users_admintokens ON admin_sessions (user_id);


-- =====================================================================
-- test_commands
-- =====================================================================
CREATE TABLE test_commands (
  id           bigint NOT NULL,   -- supplied by the commander, not generated; unique per test only
  test_id      bigint NOT NULL,
  keyword      varchar(50) NOT NULL,
  parameter    text,
  commander_id bigint DEFAULT NULL,
  "timestamp"  timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,   -- quoted: reserved word
  executed     boolean DEFAULT false,
  PRIMARY KEY (id, test_id),
  CONSTRAINT test_commands_person_sessions_id_fk
    FOREIGN KEY (commander_id) REFERENCES person_sessions (id) ON DELETE SET NULL,
  CONSTRAINT test_commands_tests_id_fk
    FOREIGN KEY (test_id) REFERENCES tests (id) ON DELETE CASCADE
);

CREATE INDEX test_commands_person_sessions_id_fk_idx ON test_commands (commander_id);
CREATE INDEX idx_test_commands_execution ON test_commands (test_id, executed, "timestamp");


-- =====================================================================
-- test_logs
-- =====================================================================
CREATE TABLE test_logs (
  booklet_id       bigint NOT NULL,
  "timestamp"      bigint NOT NULL DEFAULT 0,   -- client epoch in milliseconds, not a timestamp
  logentry         text COLLATE german2_ci,
  timestamp_server timestamptz DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_log_booklet
    FOREIGN KEY (booklet_id) REFERENCES tests (id) ON DELETE CASCADE
);

CREATE INDEX index_fk_log_booklet ON test_logs (booklet_id);


-- =====================================================================
-- test_reviews
-- =====================================================================
CREATE TABLE test_reviews (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booklet_id bigint NOT NULL,
  person_id  bigint DEFAULT NULL,
  reviewtime timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,   -- also bumped on UPDATE, see trigger below
  priority   smallint NOT NULL DEFAULT 0,   -- 0-3, despite the tinyint(1) it came from
  categories varchar(50) COLLATE german2_ci DEFAULT NULL,
  entry      text COLLATE german2_ci,
  reviewer   varchar(255) COLLATE german2_ci DEFAULT NULL,
  user_agent varchar(512) COLLATE german2_ci NOT NULL DEFAULT '',
  CONSTRAINT fk_review_booklet
    FOREIGN KEY (booklet_id) REFERENCES tests (id) ON DELETE CASCADE,
  CONSTRAINT fk_test_reviews_person
    FOREIGN KEY (person_id) REFERENCES person_sessions (id) ON DELETE CASCADE
);

CREATE INDEX index_fk_review_booklet  ON test_reviews (booklet_id);
CREATE INDEX idx_test_reviews_person  ON test_reviews (person_id);
CREATE INDEX idx_test_reviews_sorting ON test_reviews (booklet_id, person_id, reviewtime);


-- =====================================================================
-- logins
-- =====================================================================
CREATE TABLE logins (
  name              varchar(50) PRIMARY KEY,   -- no german2_ci: login names must match exactly
  password          varchar(100) COLLATE german2_ci NOT NULL,
  mode              varchar(20) COLLATE german2_ci NOT NULL,
  workspace_id      bigint DEFAULT NULL,
  codes_to_booklets text COLLATE german2_ci,
  source            varchar(120) NOT NULL,   -- was varbinary(120) for case-sensitivity, not for binary data
  valid_from        timestamptz DEFAULT NULL,
  valid_to          timestamptz DEFAULT NULL,
  valid_for         integer DEFAULT NULL,
  group_name        varchar(100) COLLATE german2_ci DEFAULT NULL,
  group_label       text COLLATE german2_ci,
  custom_texts      text COLLATE german2_ci,
  monitors          text COLLATE german2_ci,
  view_settings     text COLLATE german2_ci,
  CONSTRAINT logins_workspaces_id_fk
    FOREIGN KEY (workspace_id) REFERENCES workspaces (id) ON DELETE CASCADE
);

CREATE INDEX logins_workspaces_id_fk_idx ON logins (workspace_id);


-- =====================================================================
-- unit_logs
-- =====================================================================
CREATE TABLE unit_logs (
  unit_name   varchar(50) COLLATE german2_ci NOT NULL,
  test_id     bigint NOT NULL,
  "timestamp" bigint NOT NULL DEFAULT 0,   -- client epoch in milliseconds, not a timestamp
  logentry    text COLLATE german2_ci,
  CONSTRAINT unit_logs_fk
    FOREIGN KEY (test_id, unit_name) REFERENCES units (test_id, name) ON DELETE CASCADE
);

CREATE INDEX unit_logs_fk_idx ON unit_logs (test_id, unit_name);


-- =====================================================================
-- unit_reviews
-- =====================================================================
CREATE TABLE unit_reviews (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unit_name  varchar(50) COLLATE german2_ci NOT NULL,
  person_id  bigint DEFAULT NULL,
  test_id    bigint NOT NULL,
  reviewtime timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,   -- also bumped on UPDATE, see trigger below
  priority   smallint NOT NULL DEFAULT 0,   -- 0-3, despite the tinyint(1) it came from
  categories varchar(50) COLLATE german2_ci DEFAULT NULL,
  entry      text COLLATE german2_ci,
  reviewer   varchar(255) COLLATE german2_ci DEFAULT NULL,
  page       bigint DEFAULT NULL,
  pagelabel  varchar(255) COLLATE german2_ci DEFAULT NULL,
  user_agent varchar(512) COLLATE german2_ci NOT NULL DEFAULT '',
  CONSTRAINT fk_unit_reviews_person
    FOREIGN KEY (person_id) REFERENCES person_sessions (id) ON DELETE CASCADE,
  CONSTRAINT unit_reviews_fk
    FOREIGN KEY (test_id, unit_name) REFERENCES units (test_id, name) ON DELETE CASCADE
);

CREATE INDEX unit_reviews_unit_index  ON unit_reviews (unit_name, test_id);
CREATE INDEX idx_unit_reviews_person  ON unit_reviews (person_id);
CREATE INDEX idx_unit_reviews_sorting ON unit_reviews (test_id, unit_name, person_id, reviewtime);


-- =====================================================================
-- workspace_users
-- =====================================================================
CREATE TABLE workspace_users (
  workspace_id bigint NOT NULL,
  user_id      bigint NOT NULL,
  role         varchar(10) COLLATE german2_ci NOT NULL DEFAULT 'RW',
  PRIMARY KEY (workspace_id, user_id),
  CONSTRAINT fk_workspace_users_user
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_workspace_users_workspace
    FOREIGN KEY (workspace_id) REFERENCES workspaces (id) ON DELETE CASCADE
);

CREATE INDEX index_fk_workspace_users_user ON workspace_users (user_id);


-- =====================================================================
-- meta
-- =====================================================================
-- "metaKey" needs its quotes everywhere: PostgreSQL folds unquoted identifiers to lowercase.
-- `category` is nullable and part of the unique constraint, so the constraint does not prevent a
-- second ('dbSchemaVersion', NULL) row — InitDAO::setDBSchemaVersion() assumes there is only one.
CREATE TABLE meta (
  "metaKey" varchar(100) NOT NULL,
  value     text,
  category  varchar(30) DEFAULT NULL,
  CONSTRAINT meta_pk UNIQUE ("metaKey", category)
);


-- =====================================================================
-- unit_data
-- =====================================================================
CREATE TABLE unit_data (
  part_id       varchar(50) NOT NULL,
  unit_name     varchar(50) COLLATE german2_ci NOT NULL,
  test_id       bigint NOT NULL,
  content       text,
  ts            bigint NOT NULL DEFAULT 0,   -- client epoch in milliseconds, not a timestamp
  response_type varchar(50) DEFAULT NULL,
  PRIMARY KEY (part_id, test_id, unit_name),
  CONSTRAINT unit_data_fk
    FOREIGN KEY (test_id, unit_name) REFERENCES units (test_id, name) ON DELETE CASCADE
);

CREATE INDEX unit_data_fk_idx ON unit_data (test_id, unit_name);


-- =====================================================================
-- files
-- =====================================================================
-- `name` carries no collation, and file_relations.subject_name must match it exactly for the
-- foreign key below to be creatable — keep both sides uncollated.
CREATE TABLE files (
  workspace_id       bigint NOT NULL,
  name               varchar(120) NOT NULL,
  id                 varchar(120) COLLATE german2_ci NOT NULL,
  version_mayor      integer DEFAULT NULL,
  version_minor      integer DEFAULT NULL,
  version_patch      integer DEFAULT NULL,
  version_label      text COLLATE german2_ci,
  label              text COLLATE german2_ci,
  description        text COLLATE german2_ci,
  type               file_type NOT NULL,
  verona_module_type verona_module_type DEFAULT NULL,
  verona_version     varchar(12) COLLATE german2_ci DEFAULT NULL,
  verona_module_id   varchar(50) COLLATE german2_ci DEFAULT NULL,
  is_valid           boolean NOT NULL,
  validation_report  text COLLATE german2_ci,
  modification_ts    timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  size               integer NOT NULL,
  context_data       text COLLATE german2_ci,
  PRIMARY KEY (workspace_id, name, type),
  CONSTRAINT unique_id UNIQUE (workspace_id, id, type),
  CONSTRAINT files_workspaces_id_fk
    FOREIGN KEY (workspace_id) REFERENCES workspaces (id) ON DELETE CASCADE
);

CREATE INDEX files_workspace_id_name_index ON files (workspace_id, name);
CREATE INDEX files_id_index ON files (id);


-- =====================================================================
-- unit_defs_attachments
-- =====================================================================
-- `file_type` holds nothing but the constant 'Booklet'. It exists only so that the foreign key can
-- point at files of that type; WorkspaceDAO never writes it. MySQL used a stored generated column
-- for this, which PostgreSQL supports too — DEFAULT plus CHECK gives the same guarantee without
-- the generated-column semantics.
CREATE TABLE unit_defs_attachments (
  workspace_id    bigint NOT NULL,
  unit_name       varchar(120) COLLATE german2_ci NOT NULL,
  booklet_name    varchar(120) COLLATE german2_ci NOT NULL,
  attachment_type attachment_type NOT NULL,
  variable_id     varchar(100) COLLATE german2_ci NOT NULL,
  file_type       file_type NOT NULL DEFAULT 'Booklet',
  CONSTRAINT unit_defs_attachments_file_type_const CHECK (file_type = 'Booklet'),
  PRIMARY KEY (booklet_name, unit_name, variable_id, workspace_id),
  CONSTRAINT files_fk
    FOREIGN KEY (workspace_id, booklet_name, file_type)
    REFERENCES files (workspace_id, id, type) ON DELETE CASCADE
);

CREATE INDEX files_fk_idx ON unit_defs_attachments (workspace_id, booklet_name, file_type);


-- =====================================================================
-- file_relations
-- =====================================================================
-- WorkspaceDAO::storeRelations() inserts against unique_combination with ON CONFLICT DO NOTHING,
-- because a file may declare the same relation twice. That deduplication silently stops working
-- for any row that leaves `object_name` NULL: NULL never collides, so the constraint does not
-- catch it. The current writer always supplies a name.
CREATE TABLE file_relations (
  workspace_id      bigint NOT NULL,
  subject_name      varchar(120) NOT NULL,
  subject_type      file_type NOT NULL,
  relationship_type file_relationship_type NOT NULL,
  object_type       file_type NOT NULL,
  object_name       varchar(120) DEFAULT NULL,
  CONSTRAINT unique_combination UNIQUE (
    workspace_id, subject_name, subject_type, relationship_type, object_type, object_name
  ),
  CONSTRAINT file_relations_files_fk
    FOREIGN KEY (workspace_id, subject_name, subject_type)
    REFERENCES files (workspace_id, name, type) ON DELETE CASCADE
);


-- =====================================================================
-- assets
-- =====================================================================
CREATE TABLE assets (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  original_name varchar(255) NOT NULL,
  stored_name   varchar(255) NOT NULL,
  created_at    timestamptz DEFAULT CURRENT_TIMESTAMP,   -- was MySQL DATETIME, the schema's only timezone-less column
  CONSTRAINT assets_stored_name_key UNIQUE (stored_name),
  CONSTRAINT unique_original_name UNIQUE (original_name)
);


-- =====================================================================
-- asset_assignment
-- =====================================================================
CREATE TABLE asset_assignment (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id integer NOT NULL DEFAULT 0,   -- deliberately no foreign key, see column comment
  source       varchar(255) DEFAULT NULL,
  slot_name    varchar(100) NOT NULL,
  asset_id     integer NOT NULL,
  scope        assignment_scope NOT NULL,
  scope_id     varchar(100) NOT NULL DEFAULT 'global',
  CONSTRAINT unique_assignment UNIQUE (workspace_id, slot_name, scope, scope_id),
  CONSTRAINT asset_assignment_ibfk_1
    FOREIGN KEY (asset_id) REFERENCES assets (id) ON DELETE CASCADE
);

CREATE INDEX idx_scope ON asset_assignment (scope, scope_id);
CREATE INDEX idx_asset_assignment_source ON asset_assignment (workspace_id, source);
CREATE INDEX asset_assignment_asset_id_idx ON asset_assignment (asset_id);


-- =====================================================================
-- Column comments
-- =====================================================================
COMMENT ON COLUMN tests.name IS
  'This includes the file_id + the symbol "#" for further information for adaptivity and the pre-configured state of the test - the combination of all configs must be unique';
COMMENT ON COLUMN tests.file_id IS
  'This is the real field mapping to the booklet ID, can have same value more than once. `name` has additional information regarding adaptivity and the pre-configured state of the test.';
COMMENT ON COLUMN asset_assignment.workspace_id IS
  'Only used with source to delete XML assignments by workspace file source, not for group/user scoping.';
COMMENT ON COLUMN asset_assignment.source IS
  'XML file source used with workspace_id for delete-by-source cleanup, not for group/user scoping.';


-- =====================================================================
-- Triggers
-- =====================================================================
-- Both reviewtime columns had ON UPDATE CURRENT_TIMESTAMP in MySQL, which has no PostgreSQL
-- equivalent. No other column needs one: login_session_groups.last_modified only looked like it
-- did, because MySQL grants the first TIMESTAMP column of a table an implicit ON UPDATE — but only
-- while explicit_defaults_for_timestamp is off, and MySQL 8 defaults it on. AdminDAO writes that
-- column explicitly, so a trigger would silently discard the value it passes.
CREATE OR REPLACE FUNCTION set_reviewtime_on_update() RETURNS trigger AS $$
BEGIN
  NEW.reviewtime := CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER test_reviews_reviewtime_bu
  BEFORE UPDATE ON test_reviews
  FOR EACH ROW EXECUTE FUNCTION set_reviewtime_on_update();

CREATE TRIGGER unit_reviews_reviewtime_bu
  BEFORE UPDATE ON unit_reviews
  FOR EACH ROW EXECUTE FUNCTION set_reviewtime_on_update();


-- =====================================================================
-- Schema version
-- =====================================================================
-- Marks how far this file already carries the schema, so that initialize.php does not replay
-- patches it contains. Must name the newest patch in patches.d that is folded in here; with
-- patches.d empty it is the release this schema belongs to.
INSERT INTO meta ("metaKey", value, category)
VALUES ('dbSchemaVersion', '18.3.0', NULL);

COMMIT;
