-- IQB-Testcenter DB -- PostgreSQL
--
-- Übersetzung von scripts/database/full.sql (MySQL 8 / InnoDB) nach PostgreSQL.
-- Zielzustand: initiale Befüllung einer *leeren* Postgres-Datenbank.
--
-- Reihenfolge der Statements = Abhängigkeitsreihenfolge der Fremdschlüssel.
-- Alle Stellen ohne 1:1-Übersetzung sind mit  >>> ABWEICHUNG <<<  markiert
-- und am Dateiende unter "MIGRATIONSHINWEISE" zusammengefasst.

BEGIN;

-- =====================================================================
-- >>> ABWEICHUNG 1: CHARACTER SET / COLLATION <<<
-- MySQL: utf8mb3 / utf8mb3_german2_ci bzw. utf8mb4 / utf8mb4_0900_ai_ci
--        (ci = case-insensitive, accent-insensitive) sowie utf8mb3_bin.
-- Postgres kennt keine Per-Spalten-Charsets; die Datenbank ist UTF8.
-- Case-Insensitivity wird über eine nicht-deterministische ICU-Collation
-- nachgebildet. Diese ersetzt utf8mb3_german2_ci.
-- Empfehlung: Datenbank mit  ENCODING 'UTF8'  anlegen und diese Collation
-- an allen Textspalten verwenden, die in MySQL *_ci waren.
-- Benötigt Postgres >= 12 mit ICU-Support (ab PG 16 auch als DB-Default nutzbar).
-- =====================================================================
CREATE COLLATION IF NOT EXISTS german2_ci (
  provider      = icu,
  locale        = 'de-DE-u-ks-level2',  -- level2 = case-insensitive, akzentsensitiv
  deterministic = false
);

-- >>> ABWEICHUNG 2: ENUM-Typen <<<
-- MySQL deklariert enum(...) inline an der Spalte. Postgres benötigt
-- benannte Typen. Die Wertelisten sind 1:1 übernommen.
CREATE TYPE file_type AS ENUM (
  'Testtakers', 'SysCheck', 'Booklet', 'Unit', 'Resource'
);

CREATE TYPE verona_module_type AS ENUM (
  'player', 'schemer', 'editor', ''
);

CREATE TYPE file_relationship_type AS ENUM (
  'hasBooklet', 'containsUnit', 'usesPlayer', 'usesPlayerResource',
  'isDefinedBy', 'usesScheme', 'unknown'
);

CREATE TYPE attachment_type AS ENUM ('capture-image');

CREATE TYPE assignment_scope AS ENUM ('global', 'group', 'user');


-- =====================================================================
-- users
-- =====================================================================
-- >>> ABWEICHUNG 3: bigint unsigned <<<
-- Postgres kennt kein UNSIGNED. Alle `bigint unsigned` werden zu `bigint`.
-- Die Wertebereichshalbierung ist praktisch irrelevant; negative Werte
-- werden über CHECK-Constraints an den ID-Spalten nicht erzwungen, da
-- alle IDs aus Identity-Sequenzen stammen.
--
-- >>> ABWEICHUNG 4: AUTO_INCREMENT <<<
-- MySQL AUTO_INCREMENT -> GENERATED BY DEFAULT AS IDENTITY.
-- "BY DEFAULT" (nicht "ALWAYS"), damit explizite ID-Inserts (Tests,
-- Fixtures, Datenmigration) weiterhin möglich sind.
-- Wichtig: PDO::lastInsertId() ohne Argument nutzt unter pgsql lastval()
-- und funktioniert mit IDENTITY korrekt.
--
-- >>> ABWEICHUNG 5: tinyint(1) <<<
-- MySQL nutzt tinyint(1) als Boolean-Ersatz und liefert 0/1.
-- Hier: boolean. Siehe Migrationshinweis Nr. 5 zu den Folgen im PHP-Code.
CREATE TABLE users (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            varchar(50) COLLATE german2_ci NOT NULL,
  password        varchar(100) COLLATE german2_ci NOT NULL,
  email           varchar(100) COLLATE german2_ci DEFAULT NULL,
  is_superadmin   boolean NOT NULL DEFAULT false,
  pw_set_by_admin boolean NOT NULL DEFAULT false
);


-- =====================================================================
-- workspaces
-- =====================================================================
CREATE TABLE workspaces (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           varchar(50) COLLATE german2_ci NOT NULL,
  workspace_hash varchar(255) COLLATE german2_ci NOT NULL DEFAULT '',
  content_type   varchar(255) COLLATE german2_ci NOT NULL DEFAULT 'mixed'
);


-- =====================================================================
-- login_session_groups
-- =====================================================================
-- >>> ABWEICHUNG 6: `last_modified timestamp NOT NULL` <<<
-- In MySQL erhält die *erste* TIMESTAMP-Spalte einer Tabelle implizit
-- DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
-- (sofern explicit_defaults_for_timestamp=OFF). Postgres hat dieses
-- Verhalten nicht. Hier explizit als DEFAULT gesetzt; das ON UPDATE
-- wird über den Trigger am Dateiende nachgebildet.
--
-- >>> ABWEICHUNG 7: timestamp-Typ <<<
-- MySQL TIMESTAMP speichert UTC und konvertiert in die Session-Zeitzone.
-- Das Äquivalent ist `timestamptz`, nicht `timestamp`.
-- Empfehlung: timestamptz verwenden (hier umgesetzt) und die
-- Server-Zeitzone in postgresql.conf / im Connection-String auf UTC setzen.
CREATE TABLE login_session_groups (
  workspace_id  bigint NOT NULL,
  group_label   text COLLATE german2_ci NOT NULL,
  group_name    varchar(100) COLLATE german2_ci NOT NULL,
  token         varchar(50) COLLATE german2_ci NOT NULL,
  last_modified timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (workspace_id, group_name),
  CONSTRAINT login_session_groups_unique_token UNIQUE (token)
);


-- =====================================================================
-- login_sessions
-- =====================================================================
-- >>> ABWEICHUNG 8: utf8mb3_bin auf `name` <<<
-- `login_sessions`.`name` und `logins`.`name` sind in MySQL *_bin,
-- also case-SENSITIV — im Gegensatz zu allen anderen Spalten.
-- Das ist beabsichtigt (Login-Namen müssen exakt matchen).
-- In Postgres entspricht das der Default-Collation "C" bzw. schlicht
-- dem Weglassen der german2_ci-Collation. Hier bewusst OHNE COLLATE.
CREATE TABLE login_sessions (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         varchar(50) NOT NULL,                       -- case-sensitiv, s. Abweichung 8
  workspace_id bigint NOT NULL,
  token        varchar(50) COLLATE german2_ci NOT NULL,
  group_name   varchar(100) COLLATE german2_ci NOT NULL,
  CONSTRAINT unique_login_session UNIQUE (name, workspace_id),
  CONSTRAINT fk_login_workspace
    FOREIGN KEY (workspace_id) REFERENCES workspaces (id) ON DELETE CASCADE,
  CONSTRAINT login_session_groups_fk
    FOREIGN KEY (workspace_id, group_name)
    REFERENCES login_session_groups (workspace_id, group_name)
    ON DELETE CASCADE ON UPDATE CASCADE
);

-- >>> ABWEICHUNG 9: sekundäre Indizes <<<
-- MySQL legt KEY(...) innerhalb von CREATE TABLE an; Postgres braucht
-- separate CREATE INDEX. Redundante Indizes aus full.sql wurden dabei
-- weggelassen, siehe Migrationshinweis Nr. 9.
CREATE INDEX index_fk_login_workspace ON login_sessions (workspace_id);
CREATE INDEX index_fk_logins          ON login_sessions (name);
CREATE INDEX login_sessions_token_index ON login_sessions (token);
CREATE INDEX login_sessions_groups_fk ON login_sessions (workspace_id, group_name);
-- weggelassen: KEY `index_fk_login_session_login` (`id`) -- dupliziert den PK


-- =====================================================================
-- person_sessions
-- =====================================================================
-- >>> ABWEICHUNG 10: UNIQUE (login_sessions_id, name_suffix) mit NULL <<<
-- `name_suffix` ist nullable. MySQL wie Postgres behandeln NULL in
-- UNIQUE-Indizes als "immer verschieden", d.h. beliebig viele Zeilen mit
-- name_suffix IS NULL sind in BEIDEN Systemen erlaubt. Verhalten identisch.
-- Nur zur Info: Postgres 15+ könnte über NULLS NOT DISTINCT strenger sein;
-- das wird hier bewusst NICHT gesetzt, um MySQL-Semantik beizubehalten.
CREATE TABLE person_sessions (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code              varchar(50) COLLATE german2_ci NOT NULL,
  login_sessions_id bigint NOT NULL,
  valid_until       timestamptz DEFAULT NULL,
  token             varchar(50) COLLATE german2_ci DEFAULT NULL,
  name_suffix       varchar(100) COLLATE german2_ci DEFAULT NULL,
  CONSTRAINT unique_person_session UNIQUE (login_sessions_id, name_suffix),
  CONSTRAINT fk_person_login
    FOREIGN KEY (login_sessions_id) REFERENCES login_sessions (id) ON DELETE CASCADE
);

CREATE INDEX index_fk_person_login       ON person_sessions (login_sessions_id);
CREATE INDEX person_sessions_token_index ON person_sessions (token);
-- weggelassen: UNIQUE KEY `person_sessions_id_uindex` (`id`) -- dupliziert den PK


-- =====================================================================
-- tests
-- =====================================================================
-- >>> ABWEICHUNG 11: COMMENT <<<
-- MySQL-Spaltenkommentare werden zu COMMENT ON COLUMN (s. Dateiende).
CREATE TABLE tests (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name             varchar(250) COLLATE german2_ci NOT NULL,
  person_id        bigint NOT NULL,
  laststate        text COLLATE german2_ci,
  locked           boolean NOT NULL DEFAULT false,
  label            varchar(100) COLLATE german2_ci DEFAULT NULL,
  running          boolean NOT NULL DEFAULT false,
  timestamp_server timestamptz DEFAULT CURRENT_TIMESTAMP,
  file_id          varchar(120) COLLATE german2_ci NOT NULL,
  CONSTRAINT tests_person_id_name_key UNIQUE (person_id, name),
  CONSTRAINT fk_booklet_person
    FOREIGN KEY (person_id) REFERENCES person_sessions (id) ON DELETE CASCADE
);

CREATE INDEX index_fk_booklet_person ON tests (person_id);


-- =====================================================================
-- units
-- =====================================================================
-- Hinweis: `laststate_update_ts` ist auch in MySQL ein TEXT-Feld
-- (kein Timestamp) — 1:1 übernommen, bewusst nicht "korrigiert".
CREATE TABLE units (
  name                varchar(50) COLLATE german2_ci NOT NULL,
  test_id             bigint NOT NULL,
  laststate           text COLLATE german2_ci,
  laststate_update_ts text COLLATE german2_ci,
  original_unit_id    varchar(255) COLLATE german2_ci NOT NULL DEFAULT '',
  PRIMARY KEY (test_id, name),
  CONSTRAINT fk_unit_booklet
    FOREIGN KEY (test_id) REFERENCES tests (id) ON DELETE CASCADE
);

CREATE INDEX index_fk_unit_booklet ON units (test_id);
-- weggelassen: UNIQUE KEY `test_id` (`test_id`,`name`) -- dupliziert den PK

-- Referenzierbarkeit für die zusammengesetzten FKs aus unit_logs,
-- unit_reviews und unit_data: der PK (test_id, name) genügt bereits.


-- =====================================================================
-- admin_sessions
-- =====================================================================
-- >>> ABWEICHUNG 12: `valid_until timestamp NOT NULL ON UPDATE CURRENT_TIMESTAMP` <<<
-- Sehr wahrscheinlich ein MySQL-Altlast-Artefakt: das automatische
-- Hochsetzen von valid_until bei JEDEM UPDATE ist als Session-Verlängerung
-- semantisch fragwürdig, weil es die Ablaufzeit unkontrolliert verschiebt.
-- Empfehlung: NICHT nachbilden. Die Anwendung setzt valid_until beim
-- Anlegen/Verlängern der Session ohnehin explizit.
-- Ist das Verhalten doch gewünscht, den auskommentierten Trigger am
-- Dateiende aktivieren.
CREATE TABLE admin_sessions (
  token       varchar(50) COLLATE german2_ci PRIMARY KEY,
  user_id     bigint NOT NULL,
  valid_until timestamptz NOT NULL,
  CONSTRAINT fk_users_admintokens
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX index_fk_users_admintokens ON admin_sessions (user_id);


-- =====================================================================
-- test_commands
-- =====================================================================
-- Hinweis: `id` ist hier bewusst OHNE AUTO_INCREMENT (die ID kommt vom
-- Client/Commander), der PK ist zusammengesetzt. 1:1 übernommen.
CREATE TABLE test_commands (
  id           bigint NOT NULL,
  test_id      bigint NOT NULL,
  keyword      varchar(50) NOT NULL,
  parameter    text,
  commander_id bigint DEFAULT NULL,
  "timestamp"  timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,  -- s. Abweichung 6
  executed     boolean DEFAULT false,
  PRIMARY KEY (id, test_id),
  CONSTRAINT test_commands_person_sessions_id_fk
    FOREIGN KEY (commander_id) REFERENCES person_sessions (id) ON DELETE SET NULL,
  CONSTRAINT test_commands_tests_id_fk
    FOREIGN KEY (test_id) REFERENCES tests (id) ON DELETE CASCADE
);

CREATE INDEX test_commands_person_sessions_id_fk_idx ON test_commands (commander_id);
CREATE INDEX idx_test_commands_execution ON test_commands (test_id, executed, "timestamp");
-- weggelassen: UNIQUE KEY `test_commands_id_uindex` (`id`,`test_id`) -- dupliziert den PK


-- =====================================================================
-- test_logs
-- =====================================================================
-- Hinweis: `timestamp` ist hier ein bigint (Millisekunden-Epoch aus dem
-- Client), NICHT der timestamp-Typ. 1:1 übernommen.
CREATE TABLE test_logs (
  booklet_id       bigint NOT NULL,
  "timestamp"      bigint NOT NULL DEFAULT 0,
  logentry         text COLLATE german2_ci,
  timestamp_server timestamptz DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_log_booklet
    FOREIGN KEY (booklet_id) REFERENCES tests (id) ON DELETE CASCADE
);

CREATE INDEX index_fk_log_booklet ON test_logs (booklet_id);


-- =====================================================================
-- test_reviews
-- =====================================================================
-- `reviewtime` hat in MySQL ON UPDATE CURRENT_TIMESTAMP -> Trigger, s. Dateiende.
CREATE TABLE test_reviews (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booklet_id bigint NOT NULL,
  person_id  bigint DEFAULT NULL,
  reviewtime timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  priority   smallint NOT NULL DEFAULT 0,   -- s. Abweichung 13
  categories varchar(50) COLLATE german2_ci DEFAULT NULL,
  entry      text COLLATE german2_ci,
  reviewer   varchar(255) COLLATE german2_ci DEFAULT NULL,
  user_agent varchar(512) COLLATE german2_ci NOT NULL DEFAULT '',
  CONSTRAINT fk_review_booklet
    FOREIGN KEY (booklet_id) REFERENCES tests (id) ON DELETE CASCADE,
  CONSTRAINT fk_test_reviews_person
    FOREIGN KEY (person_id) REFERENCES person_sessions (id) ON DELETE CASCADE
);

CREATE INDEX index_fk_review_booklet   ON test_reviews (booklet_id);
CREATE INDEX idx_test_reviews_person   ON test_reviews (person_id);
CREATE INDEX idx_test_reviews_sorting  ON test_reviews (booklet_id, person_id, reviewtime);


-- =====================================================================
-- logins
-- =====================================================================
-- >>> ABWEICHUNG 14: varbinary(120) <<<
-- `source` ist varbinary, weil MySQL damit einen binären (case-sensitiven)
-- Vergleich erzwingt — nicht, weil Binärdaten gespeichert werden. Der
-- PHP-Code bindet hier durchgängig Strings (WorkspaceDAO::addLoginSource).
-- Empfehlung: varchar OHNE german2_ci (Default-Collation ist byteweise
-- und damit case-sensitiv) statt bytea. bytea würde PDO-seitig Stream-
-- Handling erzwingen und alle Vergleiche brechen.
CREATE TABLE logins (
  name              varchar(50) PRIMARY KEY,          -- case-sensitiv, s. Abweichung 8
  password          varchar(100) COLLATE german2_ci NOT NULL,
  mode              varchar(20) COLLATE german2_ci NOT NULL,
  workspace_id      bigint DEFAULT NULL,
  codes_to_booklets text COLLATE german2_ci,
  source            varchar(120) NOT NULL,            -- war varbinary(120), s. Abweichung 14
  valid_from        timestamptz DEFAULT NULL,
  valid_to          timestamptz DEFAULT NULL,
  valid_for         integer DEFAULT NULL,
  group_name        varchar(100) COLLATE german2_ci DEFAULT NULL,
  group_label       text COLLATE german2_ci,
  custom_texts      text COLLATE german2_ci,
  monitors          text COLLATE german2_ci,
  view_settings     text COLLATE german2_ci,
  CONSTRAINT logins_workspaces_id_fk
    FOREIGN KEY (workspace_id) REFERENCES workspaces (id) ON DELETE CASCADE
);

CREATE INDEX logins_workspaces_id_fk_idx ON logins (workspace_id);


-- =====================================================================
-- unit_logs
-- =====================================================================
CREATE TABLE unit_logs (
  unit_name   varchar(50) COLLATE german2_ci NOT NULL,
  test_id     bigint NOT NULL,
  "timestamp" bigint NOT NULL DEFAULT 0,
  logentry    text COLLATE german2_ci,
  CONSTRAINT unit_logs_fk
    FOREIGN KEY (test_id, unit_name) REFERENCES units (test_id, name) ON DELETE CASCADE
);

CREATE INDEX unit_logs_fk_idx ON unit_logs (test_id, unit_name);


-- =====================================================================
-- unit_reviews
-- =====================================================================
CREATE TABLE unit_reviews (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unit_name  varchar(50) COLLATE german2_ci NOT NULL,
  person_id  bigint DEFAULT NULL,
  test_id    bigint NOT NULL,
  reviewtime timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  priority   smallint NOT NULL DEFAULT 0,   -- s. Abweichung 13
  categories varchar(50) COLLATE german2_ci DEFAULT NULL,
  entry      text COLLATE german2_ci,
  reviewer   varchar(255) COLLATE german2_ci DEFAULT NULL,
  page       bigint DEFAULT NULL,
  pagelabel  varchar(255) COLLATE german2_ci DEFAULT NULL,
  user_agent varchar(512) COLLATE german2_ci NOT NULL DEFAULT '',
  CONSTRAINT fk_unit_reviews_person
    FOREIGN KEY (person_id) REFERENCES person_sessions (id) ON DELETE CASCADE,
  CONSTRAINT unit_reviews_fk
    FOREIGN KEY (test_id, unit_name) REFERENCES units (test_id, name) ON DELETE CASCADE
);

CREATE INDEX unit_reviews_unit_index    ON unit_reviews (unit_name, test_id);
CREATE INDEX idx_unit_reviews_person    ON unit_reviews (person_id);
CREATE INDEX idx_unit_reviews_sorting   ON unit_reviews (test_id, unit_name, person_id, reviewtime);


-- =====================================================================
-- workspace_users
-- =====================================================================
CREATE TABLE workspace_users (
  workspace_id bigint NOT NULL,
  user_id      bigint NOT NULL,
  role         varchar(10) COLLATE german2_ci NOT NULL DEFAULT 'RW',
  PRIMARY KEY (workspace_id, user_id),
  CONSTRAINT fk_workspace_users_user
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_workspace_users_workspace
    FOREIGN KEY (workspace_id) REFERENCES workspaces (id) ON DELETE CASCADE
);

CREATE INDEX index_fk_workspace_users_user ON workspace_users (user_id);
-- weggelassen: KEY `index_fk_workspace_users_workspace` -- Präfix des PK


-- =====================================================================
-- meta
-- =====================================================================
-- >>> ABWEICHUNG 15: mediumblob + UNIQUE mit nullable Spalte <<<
-- (a) mediumblob -> bytea wäre der Typ-Match, aber die einzige Nutzung im
--     Code ist InitDAO: "insert into meta (metaKey, value) values
--     ('dbSchemaVersion', :new_version)" — also ein String. bytea würde
--     PDO-seitig als Stream zurückkommen und den Versionsvergleich brechen.
--     Empfehlung: text. Umgesetzt.
-- (b) `category` ist nullable und Teil des UNIQUE. In MySQL wie in Postgres
--     verhindert das UNIQUE damit KEINE doppelten ('dbSchemaVersion', NULL)-
--     Zeilen. InitDAO verlässt sich auf Einmaligkeit dieser Zeile.
--     Empfehlung: category NOT NULL DEFAULT '' setzen und daraus einen
--     echten PK machen. Da das eine Verhaltensänderung ist, hier NICHT
--     stillschweigend umgesetzt — der MySQL-Zustand ist 1:1 abgebildet.
--     Der korrigierte Zustand steht auskommentiert darunter.
CREATE TABLE meta (
  "metaKey" varchar(100) NOT NULL,       -- Quoting nötig: CamelCase, s. Abweichung 16
  value     text,                        -- war mediumblob, s. Abweichung 15a
  category  varchar(30) DEFAULT NULL,
  CONSTRAINT meta_pk UNIQUE ("metaKey", category)
);
-- weggelassen: UNIQUE KEY `meta_metaKey_category_uindex` -- identisch mit meta_pk
--
-- Empfohlene Variante (bewusst nicht aktiv), s. Abweichung 15b:
-- CREATE TABLE meta (
--   "metaKey" varchar(100) NOT NULL,
--   value     text,
--   category  varchar(30) NOT NULL DEFAULT '',
--   PRIMARY KEY ("metaKey", category)
-- );


-- =====================================================================
-- unit_data
-- =====================================================================
CREATE TABLE unit_data (
  part_id       varchar(50) NOT NULL,     -- war utf8mb4_0900_ai_ci, s. Migrationshinweis 1
  unit_name     varchar(50) COLLATE german2_ci NOT NULL,
  test_id       bigint NOT NULL,
  content       text,                     -- longtext -> text (Postgres text ist unbegrenzt)
  ts            bigint NOT NULL DEFAULT 0,
  response_type varchar(50) DEFAULT NULL,
  PRIMARY KEY (part_id, test_id, unit_name),
  CONSTRAINT unit_data_fk
    FOREIGN KEY (test_id, unit_name) REFERENCES units (test_id, name) ON DELETE CASCADE
);

CREATE INDEX unit_data_fk_idx ON unit_data (test_id, unit_name);


-- =====================================================================
-- files
-- =====================================================================
-- `name` war varbinary(120) -> varchar ohne ci-Collation, s. Abweichung 14.
-- Wichtig: `name` ist Teil des PK und Ziel eines FK aus file_relations;
-- die Collation muss dort identisch sein (dort ebenfalls ohne COLLATE).
CREATE TABLE files (
  workspace_id       bigint NOT NULL,
  name               varchar(120) NOT NULL,   -- war varbinary(120)
  id                 varchar(120) COLLATE german2_ci NOT NULL,
  version_mayor      integer DEFAULT NULL,
  version_minor      integer DEFAULT NULL,
  version_patch      integer DEFAULT NULL,
  version_label      text COLLATE german2_ci,
  label              text COLLATE german2_ci,
  description        text COLLATE german2_ci,
  type               file_type NOT NULL,
  verona_module_type verona_module_type DEFAULT NULL,
  verona_version     varchar(12) COLLATE german2_ci DEFAULT NULL,
  verona_module_id   varchar(50) COLLATE german2_ci DEFAULT NULL,
  is_valid           boolean NOT NULL,
  validation_report  text COLLATE german2_ci,
  modification_ts    timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,  -- s. Abweichung 6
  size               integer NOT NULL,
  context_data       text COLLATE german2_ci,
  PRIMARY KEY (workspace_id, name, type),
  CONSTRAINT unique_id UNIQUE (workspace_id, id, type),
  CONSTRAINT files_workspaces_id_fk
    FOREIGN KEY (workspace_id) REFERENCES workspaces (id) ON DELETE CASCADE
);

CREATE INDEX files_workspace_id_name_index ON files (workspace_id, name);
CREATE INDEX files_id_index ON files (id);
-- weggelassen: KEY `file_relations_subject_index` (`workspace_id`,`name`,`type`)
--              -- identisch mit dem PK


-- =====================================================================
-- unit_defs_attachments
-- =====================================================================
-- >>> ABWEICHUNG 17: STORED GENERATED COLUMN als FK-Bestandteil <<<
-- MySQL:
--   `file_type` enum(...) GENERATED ALWAYS AS (_utf8mb4'Booklet') STORED
--   + FK (workspace_id, booklet_name, file_type) -> files(workspace_id, id, type)
-- Die Spalte ist eine Konstante, die nur existiert, um den FK auf
-- files.type = 'Booklet' einzuschränken.
--
-- Postgres erlaubt in GENERATED ALWAYS AS (...) STORED nur IMMUTABLE
-- Ausdrücke über Spalten derselben Zeile; ein reiner Konstantenausdruck
-- ist zulässig, aber Postgres verbietet Generated Columns als Ziel/Quelle
-- eines FOREIGN KEY *nicht* — der FK funktioniert.
-- Sauberer und ohne Sonderfall ist jedoch eine normale Spalte mit
-- DEFAULT + CHECK. Das ist hier umgesetzt: identische Garantie,
-- keine Generated-Column-Semantik nötig, und WorkspaceDAO:257 schreibt
-- die Spalte ohnehin nie.
-- Empfehlung: so belassen. Wer die Generated Column zwingend spiegeln
-- will, nutzt die auskommentierte Variante darunter.
CREATE TABLE unit_defs_attachments (
  workspace_id    bigint NOT NULL,
  unit_name       varchar(120) COLLATE german2_ci NOT NULL,
  booklet_name    varchar(120) COLLATE german2_ci NOT NULL,
  attachment_type attachment_type NOT NULL,
  variable_id     varchar(100) COLLATE german2_ci NOT NULL,
  file_type       file_type NOT NULL DEFAULT 'Booklet',
  CONSTRAINT unit_defs_attachments_file_type_const CHECK (file_type = 'Booklet'),
  PRIMARY KEY (booklet_name, unit_name, variable_id, workspace_id),
  CONSTRAINT files_fk
    FOREIGN KEY (workspace_id, booklet_name, file_type)
    REFERENCES files (workspace_id, id, type) ON DELETE CASCADE
);
-- Alternative, näher am MySQL-Original:
--   file_type file_type GENERATED ALWAYS AS ('Booklet'::file_type) STORED

CREATE INDEX files_fk_idx ON unit_defs_attachments (workspace_id, booklet_name, file_type);


-- =====================================================================
-- file_relations
-- =====================================================================
-- >>> ABWEICHUNG 18: UNIQUE über nullable `object_name` <<<
-- `object_name` ist nullable und Teil des UNIQUE. Verhalten in MySQL und
-- Postgres identisch (NULL != NULL), daher 1:1 übernommen.
-- Achtung: WorkspaceDAO:555 nutzt "replace into" — das muss unter Postgres
-- zu "INSERT ... ON CONFLICT ON CONSTRAINT unique_combination DO UPDATE"
-- werden, und das greift bei object_name IS NULL nicht. Siehe
-- Migrationshinweis Nr. 18.
CREATE TABLE file_relations (
  workspace_id      bigint NOT NULL,
  subject_name      varchar(120) NOT NULL,   -- war varbinary(120), s. Abweichung 14
  subject_type      file_type NOT NULL,
  relationship_type file_relationship_type NOT NULL,
  object_type       file_type NOT NULL,
  object_name       varchar(120) DEFAULT NULL,  -- war varbinary(120)
  CONSTRAINT unique_combination UNIQUE (
    workspace_id, subject_name, subject_type, relationship_type, object_type, object_name
  ),
  CONSTRAINT file_relations_files_fk
    FOREIGN KEY (workspace_id, subject_name, subject_type)
    REFERENCES files (workspace_id, name, type) ON DELETE CASCADE
);


-- =====================================================================
-- assets
-- =====================================================================
-- >>> ABWEICHUNG 19: datetime vs. timestamp <<<
-- `created_at datetime DEFAULT CURRENT_TIMESTAMP`: MySQL DATETIME ist
-- zeitzonenlos. Alle anderen Zeitspalten des Schemas sind TIMESTAMP (UTC).
-- Empfehlung: einheitlich timestamptz, damit assets nicht als einziger
-- Sonderfall zeitzonenlos bleibt. Umgesetzt.
CREATE TABLE assets (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  original_name varchar(255) NOT NULL,
  stored_name   varchar(255) NOT NULL,
  created_at    timestamptz DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT assets_stored_name_key UNIQUE (stored_name),
  CONSTRAINT unique_original_name UNIQUE (original_name)
);


-- =====================================================================
-- asset_assignment
-- =====================================================================
-- Hinweis: `workspace_id` ist hier int (nicht bigint unsigned) und hat
-- KEINEN FK auf workspaces — 1:1 aus MySQL übernommen, inkl. Kommentaren.
CREATE TABLE asset_assignment (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id integer NOT NULL DEFAULT 0,
  source       varchar(255) DEFAULT NULL,
  slot_name    varchar(100) NOT NULL,
  asset_id     integer NOT NULL,
  scope        assignment_scope NOT NULL,
  scope_id     varchar(100) NOT NULL DEFAULT 'global',
  CONSTRAINT unique_assignment UNIQUE (workspace_id, slot_name, scope, scope_id),
  CONSTRAINT asset_assignment_ibfk_1
    FOREIGN KEY (asset_id) REFERENCES assets (id) ON DELETE CASCADE
);

CREATE INDEX idx_scope ON asset_assignment (scope, scope_id);
CREATE INDEX idx_asset_assignment_source ON asset_assignment (workspace_id, source);
CREATE INDEX asset_assignment_asset_id_idx ON asset_assignment (asset_id);


-- =====================================================================
-- Spaltenkommentare (MySQL COMMENT -> COMMENT ON)
-- =====================================================================
COMMENT ON COLUMN tests.name IS
  'This includes the file_id + the symbol "#" for further information for adaptivity and the pre-configured state of the test - the combination of all configs must be unique';
COMMENT ON COLUMN tests.file_id IS
  'This is the real field mapping to the booklet ID, can have same value more than once. `name` has additional information regarding adaptivity and the pre-configured state of the test.';
COMMENT ON COLUMN asset_assignment.workspace_id IS
  'Only used with source to delete XML assignments by workspace file source, not for group/user scoping.';
COMMENT ON COLUMN asset_assignment.source IS
  'XML file source used with workspace_id for delete-by-source cleanup, not for group/user scoping.';


-- =====================================================================
-- >>> ABWEICHUNG 20: ON UPDATE CURRENT_TIMESTAMP <<<
-- MySQL aktualisiert diese Spalten automatisch bei jedem UPDATE.
-- Postgres hat kein Äquivalent; nachgebildet über BEFORE-UPDATE-Trigger.
-- Betroffen laut full.sql:
--   test_reviews.reviewtime, unit_reviews.reviewtime,
--   login_session_groups.last_modified (implizit, s. Abweichung 6),
--   admin_sessions.valid_until (bewusst NICHT nachgebildet, s. Abweichung 12)
-- =====================================================================
CREATE OR REPLACE FUNCTION set_reviewtime_on_update() RETURNS trigger AS $$
BEGIN
  NEW.reviewtime := CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER test_reviews_reviewtime_bu
  BEFORE UPDATE ON test_reviews
  FOR EACH ROW EXECUTE FUNCTION set_reviewtime_on_update();

CREATE TRIGGER unit_reviews_reviewtime_bu
  BEFORE UPDATE ON unit_reviews
  FOR EACH ROW EXECUTE FUNCTION set_reviewtime_on_update();

CREATE OR REPLACE FUNCTION set_last_modified_on_update() RETURNS trigger AS $$
BEGIN
  NEW.last_modified := CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER login_session_groups_last_modified_bu
  BEFORE UPDATE ON login_session_groups
  FOR EACH ROW EXECUTE FUNCTION set_last_modified_on_update();

-- Bewusst deaktiviert, s. Abweichung 12. Nur aktivieren, wenn das
-- MySQL-Verhalten (Session-Ablauf verschiebt sich bei jedem UPDATE)
-- wirklich reproduziert werden soll:
-- CREATE OR REPLACE FUNCTION set_valid_until_on_update() RETURNS trigger AS $$
-- BEGIN
--   NEW.valid_until := CURRENT_TIMESTAMP;
--   RETURN NEW;
-- END;
-- $$ LANGUAGE plpgsql;
-- CREATE TRIGGER admin_sessions_valid_until_bu
--   BEFORE UPDATE ON admin_sessions
--   FOR EACH ROW EXECUTE FUNCTION set_valid_until_on_update();


-- =====================================================================
-- Schema-Version
-- =====================================================================
-- full.sql selbst schreibt keine Version; InitDAO tut das nach dem
-- Einspielen der Patches. Wird dieses Skript als Ersatz für
-- base.sql + patches.d verwendet, muss die Version hier gesetzt werden,
-- sonst versucht InitDAO alle Patches erneut einzuspielen.
-- Wert = höchste Datei in scripts/database/patches.d (aktuell 18.1.0).
INSERT INTO meta ("metaKey", value, category)
VALUES ('dbSchemaVersion', '18.2.0', NULL);

COMMIT;


-- =====================================================================
-- MIGRATIONSHINWEISE — kein 1:1-Mapping, Handlungsbedarf im Code
-- =====================================================================
--
--  1. COLLATION (Abweichung 1)
--     Das MySQL-Schema mischt drei Collations: utf8mb3_german2_ci (Default),
--     utf8mb3_bin (Login-Namen, case-sensitiv) und utf8mb4_0900_ai_ci
--     (test_commands, meta, unit_data, assets, asset_assignment).
--     Abgebildet auf: german2_ci (ICU, nicht-deterministisch) bzw.
--     Default-Collation (case-sensitiv).
--     ACHTUNG: Nicht-deterministische Collations verbieten in Postgres
--     die Pattern-Operatoren LIKE/ILIKE und reguläre Ausdrücke auf der
--     betroffenen Spalte (Fehler: "nondeterministic collations are not
--     supported for LIKE"). Vor dem Rollout prüfen:
--         grep -rn "like" --include="*.php" backend/src/dao
--     Wo LIKE nötig ist, entweder
--       (a) im Query explizit umkollationieren:
--           WHERE name COLLATE "C" LIKE :pattern
--       (b) oder die Spalte deterministisch lassen und die
--           Case-Insensitivität über lower(...) + Functional Index lösen.
--     Empfehlung: (b) für Spalten, die tatsächlich mit LIKE durchsucht
--     werden; german2_ci nur dort, wo reine Gleichheitsvergleiche laufen.
--
--  2. ENUM (Abweichung 2)
--     Als eigene Typen umgesetzt. Neue Werte brauchen künftig
--     ALTER TYPE ... ADD VALUE statt ALTER TABLE ... MODIFY.
--     Alternative wäre varchar + CHECK; das ist migrationsfreundlicher,
--     weicht aber stärker vom Original ab.
--     Empfehlung: bei Typen, die absehbar wachsen (file_relationship_type),
--     varchar + CHECK erwägen.
--
--  4. AUTO_INCREMENT-Startwerte
--     full.sql enthält AUTO_INCREMENT=2 (users, workspaces), =16
--     (login_sessions, person_sessions), =33 (tests). Das sind Artefakte
--     des Dumps aus einer Testdatenbank, KEIN Zielzustand. Für eine leere
--     DB starten alle Identity-Sequenzen bei 1 — hier bewusst so.
--     Werden Daten aus MySQL übernommen, danach unbedingt:
--         SELECT setval(pg_get_serial_sequence('users','id'),
--                       COALESCE((SELECT max(id) FROM users), 0) + 1, false);
--     analog für workspaces, login_sessions, person_sessions, tests,
--     test_reviews, unit_reviews, assets, asset_assignment.
--
--  5. tinyint(1) -> boolean (Abweichung 5)
--     MySQL liefert 0/1 als String; Postgres liefert true/false (PDO: bool
--     bzw. 't'/'f' je nach Treiberversion). Strikte Vergleiche wie
--     `if ($row['locked'] === '1')` brechen.
--     Alternative ohne Codeanpassung: smallint statt boolean.
--     Empfehlung: boolean beibehalten und die Vergleichsstellen prüfen —
--     das ist der sauberere Zielzustand. Betroffen: users.is_superadmin,
--     users.pw_set_by_admin, tests.locked, tests.running,
--     test_commands.executed, files.is_valid.
--     NICHT umgestellt: test_reviews.priority und unit_reviews.priority —
--     die sind zwar als tinyint(1) deklariert, tragen aber echte
--     Prioritätsstufen (0-3), daher smallint.
--
--  9. Redundante Indizes
--     full.sql enthält mehrere Indizes, die den PK oder einen anderen
--     UNIQUE-Index duplizieren. Diese sind hier weggelassen (jeweils am
--     Ort kommentiert): person_sessions_id_uindex, units.test_id,
--     test_commands_id_uindex, index_fk_login_session_login,
--     file_relations_subject_index, meta_metaKey_category_uindex,
--     index_fk_workspace_users_workspace.
--     Das ist eine bewusste Bereinigung, keine Übersetzungslücke.
--
-- 16. Bezeichner-Case (meta."metaKey")
--     Postgres faltet unquotierte Bezeichner nach lowercase. `metaKey`
--     bleibt deshalb nur mit doppelten Anführungszeichen erhalten.
--     InitDAO.class.php:392/397 schreibt `metaKey` unquotiert —
--     das läuft unter Postgres in einen "column metakey does not exist".
--     Empfehlung: Spalte in `meta_key` umbenennen und den Code anpassen,
--     statt dauerhaft mit Quoting zu leben. Hier bewusst 1:1 belassen,
--     damit dieses Skript den Ist-Zustand abbildet.
--     Gleiches gilt für die Spaltennamen `timestamp` (test_commands,
--     test_logs, unit_logs) — reserviertes Wort, hier gequotet.
--
-- 18. REPLACE INTO
--     Kein Postgres-Äquivalent. Betroffen:
--       WorkspaceDAO:160 (files), :257 (unit_defs_attachments),
--       :555 (file_relations)
--     Zu ersetzen durch INSERT ... ON CONFLICT (...) DO UPDATE SET ...
--     Semantischer Unterschied: REPLACE löscht die alte Zeile und fügt neu
--     ein (löst damit ON DELETE CASCADE der referenzierenden Tabellen aus!),
--     ON CONFLICT DO UPDATE aktualisiert nur. Für `files` ist das relevant:
--     unter MySQL räumt ein REPLACE die abhängigen file_relations und
--     unit_defs_attachments mit ab, unter Postgres nicht.
--     Empfehlung: an diesen Stellen bewusst entscheiden — für `files`
--     vermutlich explizites DELETE + INSERT in einer Transaktion, um das
--     bisherige Verhalten zu erhalten.
--     Zusatz für file_relations: ON CONFLICT greift nicht, wenn
--     object_name NULL ist (NULL kollidiert nie). Dort entweder
--     NULLS NOT DISTINCT (PG 15+) am UNIQUE ergänzen oder object_name
--     auf NOT NULL DEFAULT '' umstellen.
--
-- 21. TRUNCATE-Statements
--     Die `TRUNCATE <table>;` nach jedem CREATE in full.sql dienen dort
--     dem Zurücksetzen des AUTO_INCREMENT nach einem Dump. Für eine leere
--     Postgres-DB sind sie gegenstandslos und wurden weggelassen.
--     (Postgres bräuchte ohnehin TRUNCATE ... RESTART IDENTITY CASCADE.)
--
-- 22. ENGINE=InnoDB / DEFAULT CHARSET
--     Ohne Entsprechung und ersatzlos entfallen — Postgres hat nur eine
--     Storage-Engine, und Transaktionalität/Referenzielle Integrität sind
--     dort Default.
