FORMAT: 1A
HOST: https://www.example.com

# IQB Testcenter API - Backend
This a spec for the (REST-) API of the IQB-Testcenter Admin-Application. It will be used to make backend's e2e-test and a mock-server for frontend's e2e-tests.
It's the basis for out vision of continuous integration.

Status:
- this file is converted from spec.yml
- alternative examples are missing
- bad examples are missing
- does it really test the correct structures?
- names!

# Login [/php/login.php/login]

## Login [POST]

+ Request (application/json)

    + Attributes (loginrequest)

+ Response 200 (application/json)

    + Attributes (loginresponse)

    + Body

            {"admintoken":"1337ymca1337666.xxx13370","name":"super","workspaces":[{"id":"1","name":"example_workspace","role":"RW"}],"is_superadmin":true}

+ Response 401

        Not authenticated

+ Response 404

        Other Error

+ Response 406

        Other Error

+ Response 500

        Server Error



# Php SysPhp Users [/php/sys.php/users{?ws}]

## get a list of users [GET]

retrieves info about all registered users - in whole application or in a workspace.

+ Parameters

    + ws (string, optional)

        id of a workspace to get users from. can be omitted for all users in system

+ Request

    + Headers

            AuthToken:{"at":"1337ymca1337666.xxx13370"}

+ Response 200 (application/json)

        List of users

    + Attributes (array[user])

+ Response 401

        Not authenticated

+ Response 500

        Server Error





# Php SysPhp User Add [/php/sys.php/user/add]

## add a user [POST]
add a user

+ Request (application/json)
    + Headers

            AuthToken:{"at":"1337ymca1337666.xxx13370"}


    + Attributes (user)



+ Response 200 (text/plain)

        OK, user has been added

    + Attributes (string)


    + Body

            true


+ Response 401 

        Not authenticated




+ Response 500 

        Server Error





# Php SysPhp User Pw [/php/sys.php/user/pw]

## change userpassword [POST]
changes the password of a given user. returns true if user does not exist.

+ Request (application/json)
    + Headers

            AuthToken:{"at":"1337ymca1337666.xxx13370"}


    + Attributes (user)



+ Response 200 (text/plain)

        password has changed / user did not exist

    + Attributes (string)


    + Body

            true


+ Response 401 

        Not authenticated




+ Response 500 

        Server Error





# Php SysPhp Users Delete [/php/sys.php/users/delete]

## delete some users [POST]
deletes a list of given user-names (not ids!). if the list containes unexistant users, nothing happens.

+ Request (application/json)
    + Headers

            AuthToken:{"at":"1337ymca1337666.xxx13370"}


    + Attributes (Php SysPhp Users Delete Request)


    + Body

            {
                "u": [
                    "secondUser"
                ]
            }


+ Response 200 (text/plain)

        OK, users has been deleted

    + Attributes (string)


    + Body

            true


+ Response 401 

        Not authenticated




+ Response 500 

        Server Error





# Php SysPhp Workspaces [/php/sys.php/workspaces{?u}]

## get a list of workspaces [GET]
get a list of all workspaces or all workspaces belonging to a given user
+ Parameters
    + u (string, optional)

        user-id or ""


+ Request 
    + Headers

            AuthToken:{"at":"1337ymca1337666.xxx13370"}





+ Response 200 (application/json)

        List of Workspaces

    + Attributes (array[workspace])



+ Response 401 

        Not authenticated




+ Response 500 

        Server Error





# Php SysPhp Workspace Add [/php/sys.php/workspace/add]

## add a workspace [POST]
adds a workspace with given name

+ Request (application/json)
    + Headers

            AuthToken:{"at":"1337ymca1337666.xxx13370"}


    + Attributes (Php SysPhp Workspace Add Request)


    + Body

            {
                "n": "new work space"
            }


+ Response 200 (text/plain)

        OK, workspace has been added

    + Attributes (string)


    + Body

            true


+ Response 401 

        Not authenticated




+ Response 500 

        Server Error





# Php SysPhp Workspace Rename [/php/sys.php/workspace/rename]

## rename a workspace [POST]
renames a workspace with given id

+ Request (application/json)
    + Headers

            AuthToken:{"at":"1337ymca1337666.xxx13370"}


    + Attributes (Php SysPhp Workspace Rename Request)


    + Body

            {
                "ws": 2,
                "n": "new york space"
            }


+ Response 200 (text/plain)

        OK, workspace has been renamed

    + Attributes (string)


    + Body

            true


+ Response 401 

        Not authenticated




+ Response 500 

        Server Error





# Php SysPhp Workspaces Delete [/php/sys.php/workspaces/delete]

## delete some workspaces [POST]
deletes a list of workspaces given by their ids

+ Request (application/json)
    + Headers

            AuthToken:{"at":"1337ymca1337666.xxx13370"}


    + Attributes (Php SysPhp Workspaces Delete Request)


    + Body

            {
                "ws": [
                    2
                ]
            }


+ Response 200 (text/plain)

        OK, workspace has been renamed

    + Attributes (string)


    + Body

            true


+ Response 401 

        Not authenticated




+ Response 500 

        Server Error





# Php SysPhp Workspace Users [/php/sys.php/workspace/users]

## change user roles [POST]
change user roles in a given workspaces

+ Request (application/json)
    + Headers

            AuthToken:{"at":"1337ymca1337666.xxx13370"}


    + Attributes (Php SysPhp Workspace Users Request)


    + Body

            {
                "ws": 1,
                "u": [
                    {
                        "role": "RO",
                        "id": 1
                    }
                ]
            }


+ Response 200 (text/plain)

        OK, roles has been updated

    + Attributes (string)


    + Body

            true


+ Response 401 

        Not authenticated




+ Response 500 

        Server Error





# Php SysPhp User Workspaces [/php/sys.php/user/workspaces]

## change user roles1 [POST]
change user roles for a given user in several workspaces. *Provide user-name, not user-id!*

+ Request (application/json)
    + Headers

            AuthToken:{"at":"1337ymca1337666.xxx13370"}


    + Attributes (Php SysPhp User Workspaces Request)


    + Body

            {
                "u": "super",
                "ws": [
                    {
                        "role": "RW",
                        "id": 1
                    }
                ]
            }


+ Response 200 (text/plain)

        OK, roles has been updated

    + Attributes (string)


    + Body

            true


+ Response 401 

        Not authenticated




+ Response 500 

        Server Error





# Php WsPhp Filelist [/php/ws.php/filelist]

## get files of workspace [GET]
get a list of all files in workspace

+ Request 
    + Headers

            AuthToken:{"at":"1337ymca1337666.xxx13370","ws":1}





+ Response 200 (application/json)

        OK, a list of files

    + Attributes (array[file])


    + Body

            [{"filename":"SAMPLE_TESTTAKERS.XML","filesize":823,"filesizestr":"823 Bytes","filedatetime":1567610586,"filedatetimestr":"04.09.2019","type":"Testtakers","typelabel":"Testtakers"},{"filename":"SAMPLE_BOOKLET.XML","filesize":1284,"filesizestr":"1.25 KB","filedatetime":1567610586,"filedatetimestr":"04.09.2019","type":"Booklet","typelabel":"Booklet"},{"filename":"SAMPLE_PLAYER.HTML","filesize":3386,"filesizestr":"3.31 KB","filedatetime":1567610586,"filedatetimestr":"04.09.2019","type":"Resource","typelabel":"Resource"},{"filename":"SAMPLE_UNIT.XML","filesize":696,"filesizestr":"696 Bytes","filedatetime":1567610586,"filedatetimestr":"04.09.2019","type":"Unit","typelabel":"Unit"},{"filename":"SAMPLE_SYSCHECK.XML","filesize":960,"filesizestr":"960 Bytes","filedatetime":1567610586,"filedatetimestr":"04.09.2019","type":"SysCheck","typelabel":"SysCheck"}]


+ Response 401 

        Not authenticated




+ Response 404 

        Workspace not found




+ Response 500 

        Server Error





# Php WsPhp Lock [/php/ws.php/lock]

## lock workspace [POST]
locks a group of booklets in a workspace

+ Request (application/json)
    + Headers

            AuthToken:{"at":"1337ymca1337666.xxx13370","ws":1}


    + Attributes (Php WsPhp Lock Request)


    + Body

            {
                "g": [
                    "group1"
                ]
            }


+ Response 200 (text/plain)

        OK

    + Attributes (string)


    + Body

            true


+ Response 401 

        Not authenticated




+ Response 404 

        Workspace not found




+ Response 500 

        Server Error





# Php WsPhp Unlock [/php/ws.php/unlock]

## unlock workspace [POST]
unlocks a group of bookltes in a workspace

+ Request (application/json)
    + Headers

            AuthToken:{"at":"1337ymca1337666.xxx13370","ws":1}


    + Attributes (Php WsPhp Unlock Request)


    + Body

            {
                "g": [
                    "group1"
                ]
            }


+ Response 200 (text/plain)

        OK

    + Attributes (string)


    + Body

            true


+ Response 401 

        Not authenticated




+ Response 404 

        Workspace not found




+ Response 500 

        Server Error





# Php WsPhp Delete [/php/ws.php/delete]

## delete files [POST]
deletes files from a workspace

+ Request (application/json)
    + Headers

            AuthToken:{"at":"1337ymca1337666.xxx13370","ws":1}


    + Attributes (Php WsPhp Delete Request)



+ Response 200 



+ Response 401 

        Not authenticated




+ Response 404 

        Workspace not found




+ Response 500 

        Server Error





# Php GetReviewsPhp [/php/getReviews.php]

## get reviews [POST]
retrieves a list of unit- and booklet-reviews for a given workspace and groups

+ Request (application/json)
    + Headers

            AuthToken:{"at":"1337ymca1337666.xxx13370","ws":1}


    + Attributes (Php GetReviewsPhp Request)


    + Body

            {
                "g": [
                    "sample_group"
                ]
            }


+ Response 200 (application/json)

        OK, list of reviews

    + Attributes (array[Php GetReviewsPhp Response])


    + Body

            [{"unitname":"UNIT.SAMPLE","bookletname":"BOOKLET.SAMPLE","groupname":"sample_group","loginname":"test","code":"euf","reviewtime":"2019-09-06 11:19:56","entry":"this is a sample unit review","priority":"1","categories":""},{"bookletname":"BOOKLET.SAMPLE","groupname":"sample_group","loginname":"test","code":"euf","reviewtime":"2019-09-06 11:19:56","entry":"sample booklet review","priority":"1","categories":"","unitname":""}]


+ Response 401 

        Not authenticated




+ Response 403 

        Forbidden




+ Response 404 

        Workspace not found




+ Response 500 

        Server Error




+ Response 503 

        Service Unavailable





# Php GetResultDataPhp [/php/getResultData.php]

## get results [POST]
retrieves a list of unit- and booklet results for a given workspace and groups

+ Request 
    + Headers

            AuthToken:{"at":"1337ymca1337666.xxx13370","ws":1}





+ Response 200 (application/json)

        OK, list of results

    + Attributes (array[Php GetResultDataPhp Response])


    + Body

            [{"groupname":"sample_group","bookletsStarted":1,"num_units_min":"1","num_units_max":"1","num_units_total":"1","lastchange":"1567776853037","num_units_mean":1}]


+ Response 401 

        Not authenticated




+ Response 403 

        Forbidden




+ Response 404 

        Workspace not found




+ Response 500 

        Server Error




+ Response 503 

        Service Unavailable





# Php GetResponsesPhp [/php/getResponses.php]

## get responses [POST]
retrieves a list of responses by a given list of groups

+ Request (application/json)
    + Headers

            AuthToken:{"at":"1337ymca1337666.xxx13370","ws":1}


    + Attributes (Php GetResponsesPhp Request)


    + Body

            {
                "g": [
                    "sample_group"
                ]
            }


+ Response 200 (application/json)

        OK, list of responses

    + Attributes (array[Php GetResponsesPhp Response])



+ Response 401 

        Not authenticated




+ Response 403 

        Forbidden




+ Response 404 

        Workspace not found




+ Response 500 

        Server Error




+ Response 503 

        Service Unavailable





# Php GetMonitorDataPhp [/php/getMonitorData.php]

## get status [POST]
retrieves an overview about running tests

+ Request 
    + Headers

            AuthToken:{"at":"1337ymca1337666.xxx13370","ws":1}





+ Response 200 (application/json)

        OK, list of monitor data

    + Attributes (array[Php GetMonitorDataPhp Response])


    + Body

            [{"groupname":"sample_group","loginsPrepared":1,"personsPrepared":10,"bookletsPrepared":10,"bookletsStarted":1,"bookletsLocked":0,"laststart":1567783156,"laststartStr":"06.09.2019"}]


+ Response 401 

        Not authenticated




+ Response 403 

        Forbidden




+ Response 404 

        Workspace not found




+ Response 500 

        Server Error




+ Response 503 

        Service Unavailable





# Php GetLogsPhp [/php/getLogs.php]

## get logs [POST]
retrieves unit and bookltes logs from this workspace

+ Request (application/json)
    + Headers

            AuthToken:{"at":"1337ymca1337666.xxx13370","ws":1}


    + Attributes (Php GetLogsPhp Request)


    + Body

            {
                "g": [
                    "sample_group"
                ]
            }


+ Response 200 (application/json)

        OK, list of logs

    + Attributes (array[Php GetLogsPhp Response])


    + Body

            [{"unitname":"UNIT.SAMPLE","bookletname":"BOOKLET.SAMPLE","groupname":"sample_group","loginname":"test","code":"sxx","timestamp":"1568026665043","logentry":"sample unit log"},{"bookletname":"BOOKLET.SAMPLE","groupname":"sample_group","loginname":"test","code":"sxx","timestamp":"1568026665043","logentry":"sample log entry","unitname":""}]


+ Response 401 

        Not authenticated




+ Response 403 

        Forbidden




+ Response 404 

        Workspace not found




+ Response 500 

        Server Error




+ Response 503 

        Service Unavailable





# Php GetBookletsStartedPhp [/php/getBookletsStarted.php]

## get started booklets [POST]
retrieves an overview about started booklets

+ Request (application/json)
    + Headers

            AuthToken:{"at":"1337ymca1337666.xxx13370","ws":1}


    + Attributes (Php GetBookletsStartedPhp Request)


    + Body

            {
                "g": [
                    "sample_group"
                ]
            }


+ Response 200 (application/json)

        OK, list of started booklets

    + Attributes (array[Php GetBookletsStartedPhp Response])


    + Body

            [{"groupname":"sample_group","loginname":"test","code":"dlu","bookletname":"BOOKLET.SAMPLE","locked":false,"lastlogin":"2019-09-10 13:29:36","laststart":"2019-09-10 13:29:37"}]


+ Response 401 

        Not authenticated




+ Response 403 

        Forbidden




+ Response 404 

        Workspace not found




+ Response 500 

        Server Error




+ Response 503 

        Service Unavailable





# Php CheckWorkspacePhp [/php/checkWorkspace.php]

## check workspace [POST]
triggers a check of all xmls in the workspace and retrieves the results

+ Response 200 (application/json)

        OK, list of reviews

    + Attributes (Php CheckWorkspacePhp Response)



+ Response 401 

        Not authenticated




+ Response 403 

        Forbidden




+ Response 404 

        Workspace not found




+ Response 500 

        Server Error




+ Response 503 

        Service Unavailable





# get file [/php/getFile.php{?ws,at,t,fn}]

## get file [GET]
retrieves a file form a goven workspace by filename
+ Parameters
    + ws (string, optional)

        workspace-id

        + Sample: 1
    + at (string, optional)

        auth token

        + Sample: 1337ymca1337666.xxx13370
    + t (string, optional)

        file type - Testtakers | Booklet | Resource | Unit | SysCheck - CASE SENSITIVE!

        + Sample: Unit
    + fn (string, optional)

        filename. - CASE SENSITIVE!

        + Sample: SAMPLE_UNIT.XML

+ Response 200 (text/xml)

        File contents

    + Attributes (object)


    + Body

            {
              "Unit": "...."
            }


+ Response 401 

        Not authenticated




+ Response 403 

        Forbidden




+ Response 404 

        workspace or file not found




+ Response 500 

        Server Error




+ Response 503 

        Service Unavailable





# Data Structures

## auth (object)


### Properties
+ `at`: `1337ymca1337666.xxx13370` (string, required) - authtoken
+ `ws` (number, optional) - workspace-id


## loginrequest (object)


### Properties
+ `n`: `super` (string, optional) - Username
+ `p`: `user123` (string, optional) - Password


## loginresponse (object)


### Properties
+ `admintoken` (string, optional) - Token for session authentication
+ `name`: `super` (string, optional) - Username repetition
+ `workspaces` (array[workspace], optional) - List of workspaces wich are open to this user
+ `is_superadmin`: `true` (boolean, optional) - Flag that tells, if this user is a superadmin


## workspace (object)


### Properties
+ `id`: `1` (string, required) 
+ `name`: `example_workspace` (string, optional) 
+ `role`: `RW` (string, optional) 
+ `selected`: `false` (boolean, optional) - TODO what does this do?


## user (object)
a user

### Properties
+ `name`: `super` (string, required) 
+ `id`: `1` (string, required) 
+ `email` (string, optional, nullable) 
+ `is_superadmin`: `1` (string, optional) 
+ `selected`: `true` (boolean, optional) - TODO what does this do?
+ `role`: `RW` (string, optional) 


## file (object)
information about a file

### Properties
+ `filename` (string, optional) 
+ `filesize` (number, optional) - file size in byte
+ `filesizestr` (string, optional) - human readable filesize
+ `filedatetime` (number, optional) - modification date as unix time stamp
+ `filedatetimestr` (string, optional) - modification date as human readable string
+ `type` (string, optional) - Testtakers | Booklet | Resource | Unit | SysCheck
+ `typelabel` (string, optional) - Testtakers | Booklet | Resource | Unit | SysCheck


## Php CheckWorkspacePhp Response (object)


### Properties
+ `errors` (array[string], optional) 
+ `warnings` (array[string], optional) 
+ `infos` (array[string], optional) 


## Php GetBookletsStartedPhp Request (object)


### Properties
+ `g` (array[string], optional) - a list


## Php GetBookletsStartedPhp Response (object)


### Properties
+ `groupname` (string, optional) 
+ `loginname` (string, optional) 
+ `code` (string, optional) - person code
+ `bookletname` (string, optional) 
+ `locked` (boolean, optional) 
+ `lastlogin` (string, optional) - date of last login and time in US format: YYYY-mm-dd HH:mm:SS
+ `laststart` (string, optional) - date of last start and time in US format: YYYY-mm-dd HH:mm:SS


## Php GetLogsPhp Request (object)


### Properties
+ `g` (array[string], optional) - a list


## Php GetLogsPhp Response (object)


### Properties
+ `unitname` (string, optional) 
+ `bookletname` (string, optional) 
+ `groupname` (string, optional) 
+ `loginname` (string, optional) 
+ `code` (string, optional) - person code
+ `timestamp` (string, optional) 
+ `logentry` (string, optional) 


## Php GetMonitorDataPhp Response (object)


### Properties
+ `groupname` (string, optional) 
+ `loginsPrepared` (number, optional) 
+ `personsPrepared` (number, optional) 
+ `bookletsPrepared` (number, optional) 
+ `bookletsStarted` (number, optional) 
+ `bookletsLocked` (number, optional) 
+ `laststart` (number, optional) - timestamp of last start
+ `laststartStr` (string, optional) - date of last start in human readable format (german date format: dd.MM.yyyy)


## Php GetResponsesPhp Request (object)


### Properties
+ `g` (array[string], optional) - a list


## Php GetResponsesPhp Response (object)


### Properties
+ `unitname` (string, optional) 
+ `responses` (string, optional) - may contain encoded JSON
+ `responsetype` (string, optional) 
+ `laststate` (string, optional) - may contain encoded JSON
+ `bookletname` (string, optional) 
+ `restorepoint_ts` (string, optional) 
+ `responses_ts` (string, optional) - contains a unix timestamp
+ `restorepoint` (string, optional) 
+ `groupname` (string, optional) 
+ `loginname` (string, optional) 
+ `code` (string, optional) - login code


## Php GetResultDataPhp Response (object)


### Properties
+ `groupname` (string, optional) 
+ `bookletsStarted` (number, optional) 
+ `num_units_min` (string, optional) 
+ `num_units_max` (string, optional) 
+ `num_units_total` (string, optional) 
+ `lastchange` (string, optional) - timestamp
+ `num_units_mean` (number, optional) 


## Php GetReviewsPhp Request (object)


### Properties
+ `g` (array[string], optional) - a list


## Php GetReviewsPhp Response (object)


### Properties
+ `unitname` (string, optional) - stays empty if booklet review
+ `bookletname` (string, optional) 
+ `groupname` (string, optional) 
+ `code` (string, optional) - login code
+ `entry` (string, optional) 
+ `priority` (string, optional) 
+ `categories` (string, optional) 


## Php SysPhp User Workspaces Request (object)


### Properties
+ `u` (string, required) - user-name (not id!)
+ `ws` (array[W], required) - array of pairs role-id


## Php SysPhp Users Delete Request (object)


### Properties
+ `u` (array[string], optional) 


## Php SysPhp Workspace Add Request (object)


### Properties
+ `n` (string, required) - Password


## Php SysPhp Workspace Rename Request (object)


### Properties
+ `ws`: `2` (number, required) - Workspace-Id
+ `n` (string, required) - Password


## Php SysPhp Workspace Users Request (object)


### Properties
+ `ws` (number, required) - Workspace-Id
+ `u` (array[U], required) - array of pairs role-id


## Php SysPhp Workspaces Delete Request (object)


### Properties
+ `ws` (array[number], required) - list of Workspace-Id


## Php WsPhp Delete Request (object)


### Properties
+ `f` (array[string], optional) - array of file names. path delimitershave to be replaced by `::`


## Php WsPhp Lock Request (object)


### Properties
+ `g` (array[string], optional) - array of group names


## Php WsPhp Unlock Request (object)


### Properties
+ `g` (array[string], optional) - array of group names


## U (object)


### Properties
+ `id` (number, optional) - user-id
+ `role` (string, optional) - role: 'RW', 'MO' or 'RO'


## W (object)


### Properties
+ `id` (number, optional) - workspace-id
+ `role` (string, optional) - role: 'RW', 'MO' or 'RO'

