openapi: 3.0.0

info:
  title: ""
  version: "%%%VERSION%%%"

paths:
  /reviews/export:
    get:
      summary: get all reviews of a person
      description: Returns a Review report in JSON or CSV format for the person associated with the token. Uses the same format as workspace/{ws_id}/report/review with useNewVersion=true.
      tags:
        - review
      parameters:
        - in: header
          name: AuthToken
          description: auth-token for a person
          example: "p:a_person_token"
          required: true
        - in: header
          name: Accept
          description: "Expected response Mimetype: 'text/csv' or 'application/json'"
          example: "text/csv"
      responses:
        "200":
          description: Reviews report in JSON or CSV format.
          content:
            text/csv;charset=utf-8:
              schema:
                type: string
              example: |-
                groupname;loginname;code;bookletname;unitname;priority;category_content;reviewtime;page;pagelabel;originalUnitId;userAgent;reviewer;entry;unitlabel;bookletlabel
                "sample_group";"test";"xxx";"BOOKLET.SAMPLE-1";"UNIT.SAMPLE";"1";"TRUE";"2021-07-29 10:00:00";"1";"page-1";"UNIT.SAMPLE";"Firefox/126.0";;"mario: this is a sample unit review";"A Sample Unit to demonstrate the SamplePlayer2";"Sample booklet"
                "sample_group";"test";"xxx";"BOOKLET.SAMPLE-1";"";"1";"TRUE";"2021-07-29 10:00:00";;;"";"Firefox/126.0";;"luigi: sample booklet review";"";"Sample booklet"
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    groupname:
                      type: string
                    loginname:
                      type: string
                    code:
                      type: string
                    bookletname:
                      type: string
                    unitname:
                      type: string
                    priority:
                      type: integer
                    category_content:
                      type: string
                    reviewtime:
                      type: string
                      format: date-time
                    page:
                      type: string
                      nullable: true
                    pagelabel:
                      type: string
                      nullable: true
                    originalUnitId:
                      type: string
                    userAgent:
                      type: string
                    reviewer:
                      type: string
                      nullable: true
                    entry:
                      type: string
                    unitlabel:
                      type: string
                    bookletlabel:
                      type: string
              example:
                - groupname: "sample_group"
                  loginname: "test"
                  code: "xxx"
                  bookletname: "BOOKLET.SAMPLE-1"
                  unitname: "UNIT.SAMPLE"
                  priority: 1
                  category_content: "TRUE"
                  reviewtime: "2021-07-29 10:00:00"
                  page: "1"
                  pagelabel: "page-1"
                  originalUnitId: "UNIT.SAMPLE"
                  userAgent: "Firefox/126.0"
                  reviewer: null
                  entry: "mario: this is a sample unit review"
                  unitlabel: "A Sample Unit to demonstrate the SamplePlayer2"
                  bookletlabel: "Sample booklet"
                - groupname: "sample_group"
                  loginname: "test"
                  code: "xxx"
                  bookletname: "BOOKLET.SAMPLE-1"
                  unitname: ""
                  priority: 1
                  category_content: "TRUE"
                  reviewtime: "2021-07-29 10:00:00"
                  page: null
                  pagelabel: null
                  originalUnitId: ""
                  userAgent: "Firefox/126.0"
                  reviewer: null
                  entry: "luigi: sample booklet review"
                  unitlabel: ""
                  bookletlabel: "Sample booklet"
        "401":
          description: Not authenticated
        "403":
          description: Forbidden
        "410":
          description: Session Expired
        "500":
          description: Server Error
